//! The committed bindings still describe the module they were generated from.
//!
//! `src/spacetime/bindings/` is generated by
//! `scripts/regenerate-spacetime-bindings.sh` and committed, because generating
//! it needs the `spacetime` CLI and CI does not install one. The cost of
//! committing a build artefact is that it can be forgotten, and a forgotten
//! regeneration is invisible: the stale bindings compile, the board connects,
//! and the one table or reducer added in the same commit is simply not there.
//!
//! This is the check that makes it visible. It is deliberately a parse of both
//! sides rather than a re-run of the generator — a test that shelled out to
//! `spacetime generate` would skip wherever the CLI is absent, which is exactly
//! CI, which is exactly where nobody is watching.
//!
//! **What it cannot catch**: a column's TYPE changing, or a reducer's
//! arguments changing. Those live inside the generated files' bodies and the
//! honest check for them is regenerating. `module_schema` covers column
//! membership and order against SQLite; this covers the table and reducer
//! inventory against the bindings.

use std::collections::BTreeSet;
use std::path::PathBuf;

fn repo_file(parts: &[&str]) -> String {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.extend(parts);
    std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()))
}

fn module_source() -> String {
    repo_file(&["spacetime", "module", "src", "lib.rs"])
}

fn bindings_index() -> String {
    repo_file(&["src", "spacetime", "bindings", "mod.rs"])
}

/// Every `accessor = <name>` in the module source.
fn module_tables() -> BTreeSet<String> {
    module_source()
        .lines()
        .filter_map(|line| {
            let rest = line
                .trim()
                .strip_prefix("#[spacetimedb::table(accessor = ")?;
            let end = rest.find([',', ')'])?;
            Some(rest[..end].to_string())
        })
        .collect()
}

/// Every callable `#[spacetimedb::reducer]` function in the module source.
///
/// **Lifecycle reducers are excluded**, and the exclusion is the generator's
/// rule rather than a convenience: `#[spacetimedb::reducer(init)]` and its
/// siblings are invoked by the store, never by a client, so the generator emits
/// no client module for them. Counting them here would make this test fail
/// against correct bindings, which is worse than not having it.
fn module_reducers() -> BTreeSet<String> {
    let source = module_source();
    let mut names = BTreeSet::new();
    let mut lines = source.lines().peekable();
    while let Some(line) = lines.next() {
        // `#[spacetimedb::reducer]` exactly — an annotation with arguments is
        // a lifecycle reducer and has no client binding.
        if line.trim() != "#[spacetimedb::reducer]" {
            continue;
        }
        // Skip doc comments and further attributes between the annotation and
        // the function it annotates.
        for inner in lines.by_ref() {
            let trimmed = inner.trim();
            if let Some(rest) = trimmed
                .strip_prefix("pub fn ")
                .or_else(|| trimmed.strip_prefix("fn "))
            {
                let end = rest
                    .find('(')
                    .unwrap_or_else(|| panic!("cannot parse the reducer signature `{trimmed}`"));
                names.insert(rest[..end].to_string());
                break;
            }
            if trimmed.starts_with("//") || trimmed.starts_with('#') || trimmed.is_empty() {
                continue;
            }
            panic!("unexpected line between a reducer annotation and its fn: `{trimmed}`");
        }
    }
    names
}

/// The `pub mod <name>;` lines in the bindings index, with the generator's
/// suffix stripped.
fn declared_bindings(suffix: &str) -> BTreeSet<String> {
    bindings_index()
        .lines()
        .filter_map(|line| {
            let name = line.trim().strip_prefix("pub mod ")?.strip_suffix(';')?;
            name.strip_suffix(suffix).map(str::to_string)
        })
        .collect()
}

const REGENERATE: &str =
    "run `./scripts/regenerate-spacetime-bindings.sh` and commit the result alongside \
     the module change";

#[test]
fn the_bindings_declare_every_module_table() {
    let module = module_tables();
    let bindings = declared_bindings("_table");

    assert!(!module.is_empty(), "sanity: the module declares tables");
    assert_eq!(
        module, bindings,
        "the committed bindings and the module disagree about which tables exist — {REGENERATE}"
    );
}

#[test]
fn the_bindings_declare_every_module_reducer() {
    let module = module_reducers();
    let bindings = declared_bindings("_reducer");

    assert!(!module.is_empty(), "sanity: the module declares reducers");
    assert_eq!(
        module, bindings,
        "the committed bindings and the module disagree about which reducers exist — {REGENERATE}"
    );
}

/// The generator stamps the CLI version it ran as. A binding set generated by a
/// different CLI than the one that builds the module is a mismatch waiting to
/// happen, and the stamp is the only evidence of it that survives into the
/// repository.
#[test]
fn the_bindings_record_which_generator_wrote_them() {
    let index = bindings_index();

    assert!(
        index.contains("generated using spacetimedb cli version"),
        "the bindings index lost its generator stamp — {REGENERATE}"
    );
}
