use std::sync::Arc;

use axum::{extract::State, http::StatusCode, Json};
use serde_json::{json, Value};

use crate::mcp::McpState;

use super::epics;
use super::learnings;
use super::review;
use super::tasks;
use super::types::{JsonRpcRequest, JsonRpcResponse};

// ---------------------------------------------------------------------------
// Tool registry macro
// ---------------------------------------------------------------------------

/// Register all MCP tools in one place. Expands to:
/// - `fn tool_definitions() -> Value` — the JSON tool list
/// - `async fn dispatch_tool(...)` — the match dispatch
/// - `pub const TOOL_NAMES: &[&str]` — flat list of names (used by setup.rs)
macro_rules! mcp_tools {
    (
        $(
            $kind:ident $name:literal => $handler:path,
                $desc:literal,
                $schema:tt
        );+ $(;)?
    ) => {
        pub(super) fn tool_definitions() -> Value {
            json!({
                "tools": [
                    $(
                        {
                            "name": $name,
                            "description": $desc,
                            "inputSchema": $schema
                        }
                    ),+
                ]
            })
        }

        pub(super) async fn dispatch_tool(
            state: &McpState,
            id: Option<Value>,
            tool_name: &str,
            args: Value,
        ) -> JsonRpcResponse {
            match tool_name {
                $(
                    $name => mcp_tools!(@call $kind, $handler, state, id, args),
                )+
                other => JsonRpcResponse::err(id, -32602, format!("Unknown tool: {other}")),
            }
        }

        pub const TOOL_NAMES: &[&str] = &[$($name),+];
    };

    (@call sync, $handler:path, $state:expr, $id:expr, $args:expr) => {
        $handler($state, $id, $args)
    };
    (@call async, $handler:path, $state:expr, $id:expr, $args:expr) => {
        $handler($state, $id, $args).await
    };
}

// ---------------------------------------------------------------------------
// Tool definitions & dispatch (generated by mcp_tools!)
// ---------------------------------------------------------------------------

mcp_tools! {
    sync "update_task" => tasks::handle_update_task,
        "Update a task's status, sub_status, title, description, repo_path, plan, and/or PR fields. At least one field besides task_id must be provided.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID"
                },
                "status": {
                    "type": "string",
                    "description": "New status: backlog, running, or review. Setting done is not allowed via MCP — ask the human operator to move the task to done from the TUI.",
                    "enum": ["backlog", "running", "review"]
                },
                "plan_path": {
                    "type": "string",
                    "description": "Absolute file path to the implementation plan"
                },
                "title": {
                    "type": "string",
                    "description": "New title for the task"
                },
                "description": {
                    "type": "string",
                    "description": "New description for the task"
                },
                "repo_path": {
                    "type": "string",
                    "description": "New repository path for the task"
                },
                "sort_order": {
                    "type": "integer",
                    "description": "Display order within column (lower values appear first)"
                },
                "pr_url": {
                    "type": "string",
                    "description": "URL of the pull request associated with this task"
                },
                "tag": {
                    "type": "string",
                    "description": "Task tag: bug, feature, chore, or epic. Controls dispatch behavior.",
                    "enum": ["bug", "feature", "chore", "epic"]
                },
                "sub_status": {
                    "type": "string",
                    "description": "Sub-status within the current status column. Running: active, needs_input, stale, crashed. Review: awaiting_review, changes_requested, approved. Must be valid for the task's current (or new) status.",
                    "enum": ["none", "active", "needs_input", "stale", "crashed", "conflict", "awaiting_review", "changes_requested", "approved"]
                },
                "epic_id": {
                    "type": "integer",
                    "description": "Link this task to an epic by ID"
                },
                "base_branch": {
                    "type": "string",
                    "description": "The base branch for rebase and PR operations (e.g. 'main', 'develop'). Defaults to 'main' if not specified."
                },
                "project_id": {
                    "type": "integer",
                    "description": "Move the task to a different project. Use list_projects to look up IDs."
                }
            },
            "required": ["task_id"]
        };

    sync "get_task" => tasks::handle_get_task,
        "Get details about a task",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID"
                }
            },
            "required": ["task_id"]
        };

    sync "create_task" => tasks::handle_create_task,
        "Create a new task on the kanban board. Tasks always start in 'backlog' status.",
        {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string",
                    "description": "Task title"
                },
                "repo_path": {
                    "type": "string",
                    "description": "Path to the repository for this task"
                },
                "description": {
                    "type": "string",
                    "description": "Task description (optional, defaults to empty)"
                },
                "plan_path": {
                    "type": "string",
                    "description": "Absolute file path to the implementation plan (optional)."
                },
                "epic_id": {
                    "type": "integer",
                    "description": "Optional epic ID to link this task to"
                },
                "sort_order": {
                    "type": "integer",
                    "description": "Display order within column (lower values appear first)"
                },
                "tag": {
                    "type": "string",
                    "description": "Task tag: bug, feature, chore, or epic. Controls dispatch behavior.",
                    "enum": ["bug", "feature", "chore", "epic"]
                },
                "base_branch": {
                    "type": "string",
                    "description": "The base branch for rebase and PR operations (e.g. 'main', 'develop'). Defaults to 'main' if not specified."
                },
                "project_id": {
                    "type": "integer",
                    "description": "Project to assign the task to. Omit to use the Default project."
                }
            },
            "required": ["title", "repo_path"]
        };

    sync "list_tasks" => tasks::handle_list_tasks,
        "List tasks on the kanban board, optionally filtered by status and/or epic.",
        {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Filter by status. Single string or array of strings.",
                    "oneOf": [
                        { "type": "string", "enum": ["backlog", "running", "review", "done", "archived"] },
                        { "type": "array", "items": { "type": "string", "enum": ["backlog", "running", "review", "done", "archived"] } }
                    ]
                },
                "epic_id": {
                    "type": "integer",
                    "description": "Filter to only tasks belonging to this epic"
                }
            }
        };

    sync "claim_task" => tasks::handle_claim_task,
        "Claim a backlog task into your current worktree. Sets the task to running and associates it with your worktree and tmux window. Only tasks in the same repo can be claimed.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID to claim"
                },
                "worktree": {
                    "type": "string",
                    "description": "Your current worktree path (from git rev-parse --show-toplevel)"
                },
                "tmux_window": {
                    "type": "string",
                    "description": "Your current tmux window name (from tmux display-message -p '#W')"
                }
            },
            "required": ["task_id", "worktree", "tmux_window"]
        };

    sync "create_epic" => epics::handle_create_epic,
        "Create a new epic on the kanban board.",
        {
            "type": "object",
            "properties": {
                "title": { "type": "string", "description": "Epic title" },
                "repo_path": { "type": "string", "description": "Repository path" },
                "description": { "type": "string", "description": "Epic description" },
                "sort_order": { "type": "integer", "description": "Display order within column (lower values appear first)" },
                "parent_epic_id": { "type": "integer", "description": "Optional parent epic ID. When set, this epic becomes a sub-epic of the specified parent. Cannot be set to the epic's own ID (self-referential cycles are rejected by the database)." },
                "project_id": { "type": "integer", "description": "Project to assign the epic to. Omit to use the Default project." }
            },
            "required": ["title", "repo_path"]
        };

    sync "get_epic" => epics::handle_get_epic,
        "Get details about an epic including its subtask summary.",
        {
            "type": "object",
            "properties": {
                "epic_id": { "type": "integer", "description": "The epic ID" }
            },
            "required": ["epic_id"]
        };

    sync "list_epics" => epics::handle_list_epics,
        "List all epics on the kanban board.",
        { "type": "object", "properties": {} };

    sync "update_epic" => epics::handle_update_epic,
        "Update an epic's title, description, status, plan, sort order, repo path, or project.",
        {
            "type": "object",
            "properties": {
                "epic_id": { "type": "integer", "description": "The epic ID" },
                "title": { "type": "string", "description": "New title" },
                "description": { "type": "string", "description": "New description" },
                "status": { "type": "string", "description": "New status: backlog, running, review, or done", "enum": ["backlog", "running", "review", "done"] },
                "plan_path": { "type": "string", "description": "Path to the plan file" },
                "sort_order": { "type": "integer", "description": "Display order within column (lower values appear first)" },
                "repo_path": { "type": "string", "description": "Repository path for the epic" },
                "project_id": { "type": "integer", "description": "Move the epic to a different project. Use list_projects to look up IDs." }
            },
            "required": ["epic_id"]
        };

    async "wrap_up" => tasks::handle_wrap_up,
        "Wrap up a running or review task. Blocks until the operation completes. rebase: rebases the task branch onto base_branch, fast-forwards base_branch, kills the tmux window, and moves the task to Done — your session ends. pr: pushes the branch, creates a draft GitHub PR targeting base_branch, and moves the task to Review; the response includes the PR URL. If a PR already exists for the branch, returns the existing URL.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID to wrap up"
                },
                "action": {
                    "type": "string",
                    "enum": ["rebase", "pr"],
                    "description": "rebase: rebase branch onto main and fast-forward. pr: push branch and create a GitHub PR."
                }
            },
            "required": ["task_id", "action"]
        };

    async "dispatch_next" => tasks::handle_dispatch_next,
        "Dispatch the next backlog subtask for an epic. Creates a worktree from main and launches a tmux session. Returns success even if there are no backlog tasks remaining.",
        {
            "type": "object",
            "properties": {
                "epic_id": {
                    "type": "integer",
                    "description": "The epic ID to dispatch the next subtask for"
                }
            },
            "required": ["epic_id"]
        };

    async "dispatch_task" => tasks::handle_dispatch_task,
        "Dispatch a backlog task by ID. Creates a worktree from the task's base branch and launches a tmux session. Waits for the dispatch to complete and returns success with worktree path and tmux window, or an error if the task is not in backlog status or the dispatch fails.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID to dispatch"
                }
            },
            "required": ["task_id"]
        };

    sync "report_usage" => tasks::handle_report_usage,
        "Report token usage and cost for a task session. Accumulates across sessions.",
        {
            "type": "object",
            "properties": {
                "task_id":            { "type": "integer", "description": "The task ID" },
                "cost_usd":           { "type": "number",  "description": "Session cost in USD" },
                "input_tokens":       { "type": "integer", "description": "Input tokens used" },
                "output_tokens":      { "type": "integer", "description": "Output tokens used" },
                "cache_read_tokens":  { "type": "integer", "description": "Cache read tokens (optional)" },
                "cache_write_tokens": { "type": "integer", "description": "Cache write tokens (optional)" }
            },
            "required": ["task_id", "cost_usd", "input_tokens", "output_tokens"]
        };

    sync "update_review_status" => tasks::handle_update_review_status,
        "Update the agent status for a dispatched review or fix agent.",
        {
            "type": "object",
            "properties": {
                "repo": {
                    "type": "string",
                    "description": "GitHub owner/repo (e.g. acme/app)"
                },
                "number": {
                    "type": "integer",
                    "description": "PR or alert number"
                },
                "status": {
                    "type": "string",
                    "description": "New agent status",
                    "enum": ["reviewing", "findings_ready", "idle"]
                }
            },
            "required": ["repo", "number", "status"]
        };

    sync "send_message" => tasks::handle_send_message,
        "Send a message/prompt to another running agent. The message is written to a file in the target's worktree and a notification is injected into their tmux window. Fire-and-forget — no response tracking.",
        {
            "type": "object",
            "properties": {
                "from_task_id": { "type": "integer", "description": "Your own task ID (the sender)" },
                "to_task_id": { "type": "integer", "description": "Target agent's task ID" },
                "body": { "type": "string", "description": "Message content to send to the other agent" }
            },
            "required": ["from_task_id", "to_task_id", "body"]
        };

    sync "list_review_prs" => review::handle_list_review_prs,
        "List review PRs from the board. Returns PRs from the most recently fetched board state.",
        {
            "type": "object",
            "properties": {
                "mode": {
                    "type": "string",
                    "description": "Filter by mode: reviewer (PRs where you are a requested reviewer), author (PRs you authored), or all (default).",
                    "enum": ["reviewer", "author", "all"]
                },
                "repo": {
                    "type": "string",
                    "description": "Filter by GitHub repo (e.g. 'acme/app'). Optional."
                }
            }
        };

    sync "get_review_pr" => review::handle_get_review_pr,
        "Get details about a specific review PR by repo and number.",
        {
            "type": "object",
            "properties": {
                "repo": {
                    "type": "string",
                    "description": "GitHub repo (e.g. 'acme/app')"
                },
                "number": {
                    "type": "integer",
                    "description": "PR number"
                }
            },
            "required": ["repo", "number"]
        };

    async "dispatch_review_agent" => review::handle_dispatch_review_agent,
        "Dispatch a review agent for a PR. Fails if an agent is already reviewing the PR.",
        {
            "type": "object",
            "properties": {
                "repo": {
                    "type": "string",
                    "description": "GitHub repo (e.g. 'acme/app')"
                },
                "number": {
                    "type": "integer",
                    "description": "PR number"
                },
                "local_repo": {
                    "type": "string",
                    "description": "Filesystem path to the local clone (e.g. '/home/user/Code/work/myrepo')"
                }
            },
            "required": ["repo", "number", "local_repo"]
        };

    sync "list_security_alerts" => review::handle_list_security_alerts,
        "List security alerts from the board. Returns alerts from the most recently fetched board state.",
        {
            "type": "object",
            "properties": {
                "repo": {
                    "type": "string",
                    "description": "Filter by GitHub repo. Optional."
                },
                "severity": {
                    "type": "string",
                    "description": "Filter by severity: critical, high, medium, or low. Optional.",
                    "enum": ["critical", "high", "medium", "low"]
                },
                "kind": {
                    "type": "string",
                    "description": "Filter by kind: dependabot or code_scanning. Optional.",
                    "enum": ["dependabot", "code_scanning"]
                }
            }
        };

    sync "get_security_alert" => review::handle_get_security_alert,
        "Get details about a specific security alert by repo, number, and kind.",
        {
            "type": "object",
            "properties": {
                "repo": {
                    "type": "string",
                    "description": "GitHub repo (e.g. 'acme/app')"
                },
                "number": {
                    "type": "integer",
                    "description": "Alert number"
                },
                "kind": {
                    "type": "string",
                    "description": "Alert kind: dependabot or code_scanning",
                    "enum": ["dependabot", "code_scanning"]
                }
            },
            "required": ["repo", "number", "kind"]
        };

    async "dispatch_fix_agent" => review::handle_dispatch_fix_agent,
        "Dispatch a fix agent for a security alert. Fails if an agent is already fixing the alert.",
        {
            "type": "object",
            "properties": {
                "repo": {
                    "type": "string",
                    "description": "GitHub repo (e.g. 'acme/app')"
                },
                "number": {
                    "type": "integer",
                    "description": "Alert number"
                },
                "kind": {
                    "type": "string",
                    "description": "Alert kind: dependabot or code_scanning",
                    "enum": ["dependabot", "code_scanning"]
                },
                "local_repo": {
                    "type": "string",
                    "description": "Filesystem path to the local clone (e.g. '/home/user/Code/work/myrepo')"
                }
            },
            "required": ["repo", "number", "kind", "local_repo"]
        };

    sync "list_projects" => handle_list_projects,
        "List all projects on the board so you can look up a project_id by name.",
        { "type": "object", "properties": {} };

    sync "record_learning" => learnings::handle_record_learning,
        "Propose a new learning entry. Always lands as 'proposed' and has no effect until a human approves it in the TUI. Omit scope_ref to auto-derive it from the calling task (recommended in most cases).",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "ID of the task this learning was discovered during"
                },
                "kind": {
                    "type": "string",
                    "description": "Category: pitfall, convention, preference, tool_recommendation, procedural, or episodic",
                    "enum": ["pitfall", "convention", "preference", "tool_recommendation", "procedural", "episodic"]
                },
                "summary": {
                    "type": "string",
                    "description": "One-sentence description of what was learned (required, non-empty)"
                },
                "scope": {
                    "type": "string",
                    "description": "Scope this learning applies to: user (global), repo, project, epic, or task",
                    "enum": ["user", "repo", "project", "epic", "task"]
                },
                "detail": {
                    "type": "string",
                    "description": "Optional extended context or explanation"
                },
                "scope_ref": {
                    "type": "string",
                    "description": "Qualifier for the scope (e.g. repo path, epic ID as string). Omit to auto-derive from the calling task — only set explicitly when recording a learning about a different context than the current task."
                },
                "tags": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Optional free-form labels for filtering (e.g. [\"rust\", \"testing\"])"
                }
            },
            "required": ["task_id", "kind", "summary", "scope"]
        };

    sync "query_learnings" => learnings::handle_query_learnings,
        "Retrieve approved learnings relevant to this task's context (user + project + repo + epic scopes). Ordered by scope priority then confirmation count. Excludes task-scoped learnings.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "ID of the calling task — determines which repo/project/epic to query"
                },
                "tag_filter": {
                    "type": "string",
                    "description": "Optional tag to filter results — only learnings tagged with this value are returned"
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum number of results to return (default 20, max 50)"
                }
            },
            "required": ["task_id"]
        };

    sync "confirm_learning" => learnings::handle_confirm_learning,
        "Signal that an approved learning was applicable and proved correct. Increments its confirmation count.",
        {
            "type": "object",
            "properties": {
                "learning_id": {
                    "type": "integer",
                    "description": "ID of the learning to confirm"
                },
                "task_id": {
                    "type": "integer",
                    "description": "ID of the task that acted on this learning"
                }
            },
            "required": ["learning_id", "task_id"]
        }
}

// ---------------------------------------------------------------------------
// list_projects handler
// ---------------------------------------------------------------------------

fn handle_list_projects(state: &McpState, id: Option<Value>, _args: Value) -> JsonRpcResponse {
    match state.db.list_projects() {
        Ok(projects) => {
            let text = projects
                .iter()
                .map(|p| {
                    if p.is_default {
                        format!("- [{}] {} (default)", p.id, p.name)
                    } else {
                        format!("- [{}] {}", p.id, p.name)
                    }
                })
                .collect::<Vec<_>>()
                .join("\n");
            JsonRpcResponse::ok(id, json!({"content": [{"type": "text", "text": text}]}))
        }
        Err(e) => JsonRpcResponse::err(id, -32603, format!("Failed to list projects: {e}")),
    }
}

// ---------------------------------------------------------------------------
// MCP handler
// ---------------------------------------------------------------------------

pub async fn handle_mcp(
    State(state): State<Arc<McpState>>,
    Json(req): Json<JsonRpcRequest>,
) -> (StatusCode, Json<JsonRpcResponse>) {
    let id = req.id;
    let response = match req.method.as_str() {
        "initialize" => JsonRpcResponse::ok(
            id,
            json!({
                "protocolVersion": "2024-11-05",
                "capabilities": {
                    "tools": {}
                },
                "serverInfo": {
                    "name": "dispatch",
                    "version": "0.1.0"
                }
            }),
        ),

        "tools/list" => JsonRpcResponse::ok(id, tool_definitions()),

        "tools/call" => {
            let params = req.params.unwrap_or(Value::Null);
            let tool_name = params.get("name").and_then(Value::as_str).unwrap_or("");
            let args = params.get("arguments").cloned().unwrap_or(Value::Null);

            dispatch_tool(&state, id, tool_name, args).await
        }

        other => JsonRpcResponse::err(id, -32601, format!("Method not found: {other}")),
    };

    (StatusCode::OK, Json(response))
}
