use std::sync::Arc;

use axum::{
    extract::State,
    http::StatusCode,
    response::{IntoResponse, Response},
    Extension, Json,
};
use serde_json::{json, Value};

use crate::mcp::identity::{CallerIdentity, IdentityError};
use crate::mcp::trajectory;
use crate::mcp::McpState;
use chrono::Utc;

use super::epics;
use super::learnings;
use super::repo_rag;
use super::tasks;
use super::types::{tool_error, JsonRpcRequest, JsonRpcResponse};

/// MCP protocol version this server speaks natively.
const SERVER_PROTOCOL_VERSION: &str = "2025-06-18";

/// Older protocol versions we still understand. If a client offers one of these
/// during `initialize`, we echo it back so the session uses that version
/// (graceful downgrade per spec §Initialization).
const SUPPORTED_PROTOCOL_VERSIONS: &[&str] = &["2025-06-18", "2024-11-05"];

// ---------------------------------------------------------------------------
// Tool registry macro
// ---------------------------------------------------------------------------

/// Register all MCP tools in one place. Expands to:
/// - `fn tool_definitions() -> Value` — the JSON tool list
/// - `async fn dispatch_tool(...)` — the match dispatch
/// - `pub const TOOL_NAMES: &[&str]` — flat list of names (used by setup.rs)
macro_rules! mcp_tools {
    (
        $(
            $kind:ident $name:literal => $handler:path,
                $desc:literal,
                $schema:tt
        );+ $(;)?
    ) => {
        pub(super) fn tool_definitions() -> Value {
            json!({
                "tools": [
                    $(
                        {
                            "name": $name,
                            "description": $desc,
                            "inputSchema": $schema
                        }
                    ),+
                ]
            })
        }

        pub(super) async fn dispatch_tool(
            state: &McpState,
            id: Option<Value>,
            identity: &CallerIdentity,
            tool_name: &str,
            args: Value,
        ) -> JsonRpcResponse {
            match tool_name {
                $(
                    $name => mcp_tools!(@call $kind, $handler, state, id, identity, args),
                )+
                other => JsonRpcResponse::err(id, -32602, format!("Unknown tool: {other}")),
            }
        }

        pub const TOOL_NAMES: &[&str] = &[$($name),+];
    };

    (@call sync, $handler:path, $state:expr, $id:expr, $identity:expr, $args:expr) => {
        $handler($state, $id, $identity, $args)
    };
    (@call async, $handler:path, $state:expr, $id:expr, $identity:expr, $args:expr) => {
        $handler($state, $id, $identity, $args).await
    };
}

// ---------------------------------------------------------------------------
// Tool definitions & dispatch (generated by mcp_tools!)
// ---------------------------------------------------------------------------

mcp_tools! {
    async "update_task" => tasks::handle_update_task,
        "Update a task's status, sub_status, title, description, repo_path, plan, and/or PR fields. At least one field besides task_id must be provided.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID"
                },
                "status": {
                    "type": "string",
                    "description": "New status: backlog, running, or review. Setting done is not allowed via MCP — ask the human operator to move the task to done from the TUI.",
                    "enum": ["backlog", "running", "review"]
                },
                "plan_path": {
                    "type": "string",
                    "description": "Absolute file path to the implementation plan"
                },
                "title": {
                    "type": "string",
                    "description": "New title for the task"
                },
                "description": {
                    "type": "string",
                    "description": "New description for the task"
                },
                "repo_path": {
                    "type": "string",
                    "description": "New repository path for the task"
                },
                "sort_order": {
                    "type": "integer",
                    "description": "Display order within column (lower values appear first)"
                },
                "pr_url": {
                    "type": "string",
                    "description": "URL of the pull request associated with this task"
                },
                "tag": {
                    "type": "string",
                    "description": "Task tag: bug, feature, chore, pr-review, research, fix, or dependabot. Controls dispatch behavior. The dependabot tag is intended for feed scripts only — TUI users cannot select it from the tag picker.",
                    "enum": ["bug", "feature", "chore", "pr-review", "research", "fix", "dependabot"]
                },
                "sub_status": {
                    "type": "string",
                    "description": "Sub-status within the current status column. Running: active, needs_input, stale, crashed. Review: awaiting_review, changes_requested, approved. Must be valid for the task's current (or new) status.",
                    "enum": ["none", "active", "needs_input", "stale", "crashed", "conflict", "awaiting_review", "changes_requested", "approved"]
                },
                "epic_id": {
                    "type": "integer",
                    "description": "Link this task to an epic by ID"
                },
                "base_branch": {
                    "type": "string",
                    "description": "The base branch for rebase and PR operations (e.g. 'main', 'develop'). Defaults to 'main' if not specified."
                },
                "project_id": {
                    "type": "integer",
                    "description": "Move the task to a different project. Use list_projects to look up IDs."
                }
            },
            "required": ["task_id"]
        };

    async "get_task" => tasks::handle_get_task,
        "Get details about a task",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID"
                }
            },
            "required": ["task_id"]
        };

    async "create_task" => tasks::handle_create_task,
        "Create a new task on the kanban board. Tasks always start in 'backlog' status. Caller identity is provided by the dispatch HTTP transport (X-Caller-Task-Id for dispatched agents, X-Caller-Kind: session for non-dispatched sessions) — you do NOT pass a caller_task_id argument. Dispatched agents: the new task inherits project_id and epic_id from your task; pass project_id or epic_id explicitly to override (epic_id: null clears epic). Non-dispatched sessions: project_id is required.",
        {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string",
                    "description": "Task title"
                },
                "repo_path": {
                    "type": "string",
                    "description": "Path to the repository for this task"
                },
                "description": {
                    "type": "string",
                    "description": "Task description (optional, defaults to empty)"
                },
                "plan_path": {
                    "type": "string",
                    "description": "Absolute file path to the implementation plan (optional)."
                },
                "epic_id": {
                    "type": ["integer", "null"],
                    "description": "Override the inherited epic. Omit to inherit from the caller's task (when the caller is a dispatched agent). Pass null explicitly to create a task with no epic even when the caller has one."
                },
                "sort_order": {
                    "type": "integer",
                    "description": "Display order within column (lower values appear first)"
                },
                "tag": {
                    "type": "string",
                    "description": "Task tag: bug, feature, chore, pr-review, research, fix, or dependabot. Controls dispatch behavior. The dependabot tag is intended for feed scripts only — TUI users cannot select it from the tag picker.",
                    "enum": ["bug", "feature", "chore", "pr-review", "research", "fix", "dependabot"]
                },
                "base_branch": {
                    "type": "string",
                    "description": "The base branch for rebase and PR operations (e.g. 'main', 'develop'). Defaults to 'main' if not specified."
                },
                "project_id": {
                    "type": "integer",
                    "description": "Override the inherited project. Omit to inherit from the caller's task (when the caller is a dispatched agent). Required when the caller is a non-dispatched session."
                }
            },
            "required": ["title", "repo_path"]
        };

    async "list_tasks" => tasks::handle_list_tasks,
        "List tasks on the kanban board. Filters are ANDed. When called by a dispatched agent, results auto-scope to the agent's epic (or project if it has no epic) and exclude the agent's own task; passing explicit epic_id/project_id/repo_paths disables auto-scoping. When called from a non-dispatched session, no auto-scoping. Output includes PR URL and plan goal when available.",
        {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Filter by status. Single string or array of strings.",
                    "oneOf": [
                        { "type": "string", "enum": ["backlog", "running", "review", "done", "archived"] },
                        { "type": "array", "items": { "type": "string", "enum": ["backlog", "running", "review", "done", "archived"] } }
                    ]
                },
                "epic_id": {
                    "type": "integer",
                    "description": "Filter to only tasks belonging to this epic."
                },
                "project_id": {
                    "type": "integer",
                    "description": "Filter to only tasks in this project."
                },
                "repo_paths": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Filter to tasks whose repo_path is in this list."
                }
            }
        };

    async "claim_task" => tasks::handle_claim_task,
        "Claim a backlog task into your current worktree. Sets the task to running and associates it with your worktree and tmux window. Only tasks in the same repo can be claimed.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID to claim"
                },
                "worktree": {
                    "type": "string",
                    "description": "Your current worktree path (from git rev-parse --show-toplevel)"
                },
                "tmux_window": {
                    "type": "string",
                    "description": "Your current tmux window name (from tmux display-message -p '#W')"
                }
            },
            "required": ["task_id", "worktree", "tmux_window"]
        };

    async "create_epic" => epics::handle_create_epic,
        "Create a new epic on the kanban board.",
        {
            "type": "object",
            "properties": {
                "title": { "type": "string", "description": "Epic title" },
                "repo_path": { "type": "string", "description": "Repository path" },
                "description": { "type": "string", "description": "Epic description" },
                "sort_order": { "type": "integer", "description": "Display order within column (lower values appear first)" },
                "parent_epic_id": { "type": "integer", "description": "Optional parent epic ID. When set, this epic becomes a sub-epic of the specified parent. Cannot be set to the epic's own ID (self-referential cycles are rejected by the database)." },
                "project_id": { "type": "integer", "description": "Project to assign the epic to. Omit to use the Default project." }
            },
            "required": ["title", "repo_path"]
        };

    async "get_epic" => epics::handle_get_epic,
        "Get details about an epic including its subtask summary.",
        {
            "type": "object",
            "properties": {
                "epic_id": { "type": "integer", "description": "The epic ID" }
            },
            "required": ["epic_id"]
        };

    async "list_epics" => epics::handle_list_epics,
        "List all epics on the kanban board.",
        { "type": "object", "properties": {} };

    async "update_epic" => epics::handle_update_epic,
        "Update an epic's title, description, status, plan, sort order, repo path, project, feed configuration, or parent epic.",
        {
            "type": "object",
            "properties": {
                "epic_id": { "type": "integer", "description": "The epic ID" },
                "title": { "type": "string", "description": "New title" },
                "description": { "type": "string", "description": "New description" },
                "status": { "type": "string", "description": "New status: backlog, running, review, or done", "enum": ["backlog", "running", "review", "done"] },
                "plan_path": { "type": "string", "description": "Path to the plan file" },
                "sort_order": { "type": "integer", "description": "Display order within column (lower values appear first)" },
                "repo_path": { "type": "string", "description": "Repository path for the epic" },
                "project_id": { "type": "integer", "description": "Move the epic to a different project. Use list_projects to look up IDs." },
                "feed_command": { "type": ["string", "null"], "description": "Shell command that emits JSON FeedItems to populate tasks. Pass null to clear." },
                "feed_interval_secs": { "type": ["integer", "null"], "description": "Polling interval in seconds (overrides the default). Pass null to clear." },
                "group_by_repo": { "type": "boolean", "description": "When true, group feed tasks by repository path in the TUI. Pass false to disable grouping." },
                "parent_epic_id": { "type": ["integer", "null"], "description": "Re-parent this epic under another epic by ID. Pass null to make it a root epic. Cycle detection prevents hierarchical loops." }
            },
            "required": ["epic_id"]
        };

    async "wrap_up" => tasks::handle_wrap_up,
        "Wrap up a running or review task. \
'rebase' rebases onto base_branch and fast-forwards it (blocks until complete) — response includes an exit token you MUST pass to exit_session. \
'done' marks the task Done immediately with no git operations — response also includes an exit token. \
'pr' records the PR URL (required pr_url arg) and moves the task to Review — no exit token, do NOT call exit_session. \
PR polling drives the task to Done on merge.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID to wrap up"
                },
                "action": {
                    "type": "string",
                    "enum": ["rebase", "done", "pr"],
                    "description": "'rebase' — rebase onto base_branch and fast-forward it (returns exit token). 'done' — mark task Done immediately, no git ops (returns exit token). 'pr' — record PR URL and move to review, no exit token."
                },
                "pr_url": {
                    "type": "string",
                    "description": "Required when action is 'pr'. The GitHub PR URL returned by gh pr create."
                },
                "learning_verdicts": {
                    "type": "array",
                    "description": "Optional per-learning verdicts for entries retrieved during this task. Submit at wrap-up to confirm or flag knowledge that was surfaced. helped → upvotes; unused → recorded only; wrong → routes the entry to needs_review.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "learning_id": { "type": "integer" },
                            "verdict": { "type": "string", "enum": ["helped", "unused", "wrong"] }
                        },
                        "required": ["learning_id", "verdict"]
                    }
                }
            },
            "required": ["task_id", "action"]
        };

    async "dispatch_next" => tasks::handle_dispatch_next,
        "Dispatch the next backlog subtask for an epic. Creates a worktree from the task's base_branch (origin/<base_branch> when reachable) and launches a tmux session. Returns success even if there are no backlog tasks remaining.",
        {
            "type": "object",
            "properties": {
                "epic_id": {
                    "type": "integer",
                    "description": "The epic ID to dispatch the next subtask for"
                }
            },
            "required": ["epic_id"]
        };

    async "dispatch_task" => tasks::handle_dispatch_task,
        "Dispatch a backlog task by ID. Creates a worktree from the task's base branch and launches a tmux session. Waits for the dispatch to complete and returns success with worktree path and tmux window, or an error if the task is not in backlog status or the dispatch fails.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID to dispatch"
                }
            },
            "required": ["task_id"]
        };

    async "send_message" => tasks::handle_send_message,
        "Send a message/prompt to another running agent. The message is written to a file in the target's worktree and a notification is injected into their tmux window. Fire-and-forget — no response tracking.",
        {
            "type": "object",
            "properties": {
                "from_task_id": { "type": "integer", "description": "Your own task ID (the sender)" },
                "to_task_id": { "type": "integer", "description": "Target agent's task ID" },
                "body": { "type": "string", "description": "Message content to send to the other agent" }
            },
            "required": ["from_task_id", "to_task_id", "body"]
        };

    async "list_projects" => handle_list_projects,
        "List all projects on the board so you can look up a project_id by name.",
        { "type": "object", "properties": {} };

    async "record_learning" => learnings::handle_record_learning,
        "Record a new entry in the shared knowledge base. The entry is immediately active and will be injected into future dispatch prompts for agents working in the matching scope. Omit scope_ref to auto-derive it from the calling task (recommended in most cases).",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "ID of the task this learning was discovered during"
                },
                "kind": {
                    "type": "string",
                    "description": "Category: pitfall, convention, preference, tool_recommendation, procedural, or landscape",
                    "enum": ["pitfall", "convention", "preference", "tool_recommendation", "procedural", "landscape"]
                },
                "summary": {
                    "type": "string",
                    "description": "One-sentence description of what was learned (required, non-empty)"
                },
                "scope": {
                    "type": "string",
                    "description": "Scope this learning applies to: user (global), repo, project, epic, or task",
                    "enum": ["user", "repo", "project", "epic", "task"]
                },
                "detail": {
                    "type": "string",
                    "description": "Optional extended context or explanation"
                },
                "scope_ref": {
                    "type": "string",
                    "description": "Qualifier for the scope (e.g. repo path, epic ID as string). Omit to auto-derive from the calling task — only set explicitly when recording a learning about a different context than the current task."
                },
                "tags": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Optional free-form labels for filtering (e.g. [\"rust\", \"testing\"])"
                }
            },
            "required": ["task_id", "kind", "summary", "scope"]
        };

    async "query_learnings" => learnings::handle_query_learnings,
        "Query the knowledge base for entries relevant to the current task's context using semantic search (RAG). Excludes task-scoped entries.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "ID of the calling task — determines which repo/project/epic to use for scope boosting"
                },
                "query": {
                    "type": "string",
                    "description": "Optional semantic query string. When omitted, the task's title and description are used as the query."
                },
                "tag_filter": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Optional list of tags to soft-boost — learnings with matching tags score higher but untagged entries are not excluded"
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum number of results to return (default 50, max 50)"
                }
            },
            "required": ["task_id"]
        };

    async "upvote_learning" => learnings::handle_upvote_learning,
        "Signal that a knowledge base entry proved useful during this task. Increments its upvote count.",
        {
            "type": "object",
            "properties": {
                "learning_id": {
                    "type": "integer",
                    "description": "ID of the knowledge base entry to upvote"
                },
                "task_id": {
                    "type": "integer",
                    "description": "ID of the task that acted on this entry"
                }
            },
            "required": ["learning_id", "task_id"]
        };

    async "set_verify_command" => tasks::handle_set_verify_command,
        "Set or clear the verify command for a repository path. \
The command is injected into future agent prompts as a mandatory pre-completion check. \
Pass command=null to clear it.",
        {
            "type": "object",
            "properties": {
                "repo_path": {
                    "type": "string",
                    "description": "Absolute path to the repository root (e.g. the task's repo_path)"
                },
                "command": {
                    "type": "string",
                    "description": "Single-line shell command to run for verification. Omit or pass null to clear."
                }
            },
            "required": ["repo_path"]
        };

    async "exit_session" => tasks::handle_exit_session,
        "Close your agent session. Two-phase: first call returns a reflection prompt asking you to call \
record_learning for any pitfalls/conventions/tips you found; the second call (with the same token) closes \
the session.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The ID of the task whose session to close"
                },
                "token": {
                    "type": "string",
                    "description": "Exit token obtained from wrap_up. Pass the same token on both the reflection call and the closing call."
                }
            },
            "required": ["task_id", "token"]
        };

    async "index_repo" => repo_rag::handle_index_repo,
        "Index (or re-index) markdown files in a repository for semantic search. Creates .dispatch/rag.db in the repo. Safe to re-run — only changed files are re-embedded. Defaults repo_path to the calling task's repo when omitted.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "ID of the calling task — used to look up repo_path when repo_path is omitted"
                },
                "repo_path": {
                    "type": "string",
                    "description": "Absolute path to the repository root. Omit to use the calling task's repo_path."
                }
            },
            "required": ["task_id"]
        };

    async "search_docs" => repo_rag::handle_search_docs,
        "Semantic search over markdown files in a repository. Returns ranked chunks with file path and score. Returns empty results (not an error) when the repo has not been indexed yet — call index_repo first.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "ID of the calling task — used to look up repo_path when repo_path is omitted"
                },
                "query": {
                    "type": "string",
                    "description": "Natural language search query"
                },
                "repo_path": {
                    "type": "string",
                    "description": "Absolute path to the repository root. Omit to use the calling task's repo_path."
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum results to return (default 5, max 20)"
                }
            },
            "required": ["task_id", "query"]
        }
}

// ---------------------------------------------------------------------------
// list_projects handler
// ---------------------------------------------------------------------------

async fn handle_list_projects(
    state: &McpState,
    id: Option<Value>,
    _identity: &CallerIdentity,
    _args: Value,
) -> JsonRpcResponse {
    match state.db.list_projects().await {
        Ok(projects) => {
            let text = projects
                .iter()
                .map(|p| {
                    if p.is_default {
                        format!("- [{}] {} (default)", p.id, p.name)
                    } else {
                        format!("- [{}] {}", p.id, p.name)
                    }
                })
                .collect::<Vec<_>>()
                .join("\n");
            JsonRpcResponse::ok(id, json!({"content": [{"type": "text", "text": text}]}))
        }
        Err(e) => JsonRpcResponse::err(id, -32603, format!("Failed to list projects: {e}")),
    }
}

// ---------------------------------------------------------------------------
// MCP handler
// ---------------------------------------------------------------------------

pub async fn handle_mcp(
    State(state): State<Arc<McpState>>,
    Extension(identity_result): Extension<Result<CallerIdentity, IdentityError>>,
    Json(req): Json<JsonRpcRequest>,
) -> Response {
    // JSON-RPC 2.0 §4.1: a Notification (no `id`) must never receive a reply.
    // MCP streamable-HTTP maps this to HTTP 202 Accepted with no body. Replying
    // to `notifications/initialized` (which Claude Code always sends after
    // `initialize`) with `id: null` breaks the client's response schema and
    // aborts the session.
    if req.id.is_none() {
        tracing::debug!(method = %req.method, "received MCP notification (no reply)");
        return StatusCode::ACCEPTED.into_response();
    }

    let id = req.id;
    let response = match req.method.as_str() {
        "initialize" => {
            // Per spec: if the client offers a version we support, echo it
            // back to use that version for the session; otherwise reply with
            // our latest supported version (the client may then abort).
            let client_version = req
                .params
                .as_ref()
                .and_then(|p| p.get("protocolVersion"))
                .and_then(Value::as_str);
            let negotiated = match client_version {
                Some(v) if SUPPORTED_PROTOCOL_VERSIONS.contains(&v) => v,
                _ => SERVER_PROTOCOL_VERSION,
            };
            JsonRpcResponse::ok(
                id,
                json!({
                    "protocolVersion": negotiated,
                    "capabilities": {
                        "tools": {}
                    },
                    "serverInfo": {
                        "name": "dispatch",
                        "version": "0.1.0"
                    }
                }),
            )
        }

        "ping" => JsonRpcResponse::ok(id, json!({})),

        "tools/list" => JsonRpcResponse::ok(id, tool_definitions()),

        "tools/call" => match identity_result.as_ref() {
            Err(e) => JsonRpcResponse::err(id, -32600, e.to_string()),
            Ok(identity) => {
                let params = req.params.unwrap_or(Value::Null);
                let tool_name = params.get("name").and_then(Value::as_str).unwrap_or("");
                let args = params.get("arguments").cloned().unwrap_or(Value::Null);

                let start = std::time::Instant::now();
                let start_utc = Utc::now();
                let resp = dispatch_tool(&state, id, identity, tool_name, args.clone()).await;

                if let CallerIdentity::Task(task_id) = identity {
                    let duration_ms = start.elapsed().as_millis() as u64;
                    let result_value = match &resp.error {
                        Some(err) => serde_json::json!({"error": err.message}),
                        None => resp.result.clone().unwrap_or(Value::Null),
                    };
                    let worktree = state
                        .db
                        .get_task(*task_id)
                        .await
                        .ok()
                        .flatten()
                        .and_then(|t| t.worktree);
                    if let Some(worktree) = worktree {
                        let entry = trajectory::TrajectoryEntry {
                            timestamp: start_utc,
                            task_id: task_id.0,
                            method: tool_name.to_string(),
                            args,
                            result: result_value,
                            duration_ms,
                        };
                        let _ = tokio::spawn(async move {
                            trajectory::append_entry(std::path::Path::new(&worktree), &entry).await;
                        });
                    }
                }

                // Per MCP spec, tool-execution failures belong in `result` with
                // `isError: true` — not as a JSON-RPC protocol error. Re-wrap any
                // error returned by the tool dispatch path.
                match resp.error {
                    Some(err) => tool_error(resp.id, err.message),
                    None => resp,
                }
            }
        },

        other => JsonRpcResponse::err(id, -32601, format!("Method not found: {other}")),
    };

    (StatusCode::OK, Json(response)).into_response()
}
