// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ArchiveStaleLearningsArgs {
    pub cutoff: String,
}

impl From<ArchiveStaleLearningsArgs> for super::Reducer {
    fn from(args: ArchiveStaleLearningsArgs) -> Self {
        Self::ArchiveStaleLearnings {
            cutoff: args.cutoff,
        }
    }
}

impl __sdk::InModule for ArchiveStaleLearningsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `archive_stale_learnings`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait archive_stale_learnings {
    /// Request that the remote module invoke the reducer `archive_stale_learnings` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`archive_stale_learnings:archive_stale_learnings_then`] to run a callback after the reducer completes.
    fn archive_stale_learnings(&self, cutoff: String) -> __sdk::Result<()> {
        self.archive_stale_learnings_then(cutoff, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `archive_stale_learnings` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn archive_stale_learnings_then(
        &self,
        cutoff: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl archive_stale_learnings for super::RemoteReducers {
    fn archive_stale_learnings_then(
        &self,
        cutoff: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ArchiveStaleLearningsArgs { cutoff }, callback)
    }
}
