// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BatchDeleteArgs {
    pub task_ids: Vec<i64>,
    pub epic_ids: Vec<i64>,
}

impl From<BatchDeleteArgs> for super::Reducer {
    fn from(args: BatchDeleteArgs) -> Self {
        Self::BatchDelete {
            task_ids: args.task_ids,
            epic_ids: args.epic_ids,
        }
    }
}

impl __sdk::InModule for BatchDeleteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `batch_delete`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait batch_delete {
    /// Request that the remote module invoke the reducer `batch_delete` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`batch_delete:batch_delete_then`] to run a callback after the reducer completes.
    fn batch_delete(&self, task_ids: Vec<i64>, epic_ids: Vec<i64>) -> __sdk::Result<()> {
        self.batch_delete_then(task_ids, epic_ids, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `batch_delete` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn batch_delete_then(
        &self,
        task_ids: Vec<i64>,
        epic_ids: Vec<i64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl batch_delete for super::RemoteReducers {
    fn batch_delete_then(
        &self,
        task_ids: Vec<i64>,
        epic_ids: Vec<i64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(BatchDeleteArgs { task_ids, epic_ids }, callback)
    }
}
