// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::sub_status_update_type::SubStatusUpdate;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BatchPatchSubStatusArgs {
    pub updates: Vec<SubStatusUpdate>,
}

impl From<BatchPatchSubStatusArgs> for super::Reducer {
    fn from(args: BatchPatchSubStatusArgs) -> Self {
        Self::BatchPatchSubStatus {
            updates: args.updates,
        }
    }
}

impl __sdk::InModule for BatchPatchSubStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `batch_patch_sub_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait batch_patch_sub_status {
    /// Request that the remote module invoke the reducer `batch_patch_sub_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`batch_patch_sub_status:batch_patch_sub_status_then`] to run a callback after the reducer completes.
    fn batch_patch_sub_status(&self, updates: Vec<SubStatusUpdate>) -> __sdk::Result<()> {
        self.batch_patch_sub_status_then(updates, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `batch_patch_sub_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn batch_patch_sub_status_then(
        &self,
        updates: Vec<SubStatusUpdate>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl batch_patch_sub_status for super::RemoteReducers {
    fn batch_patch_sub_status_then(
        &self,
        updates: Vec<SubStatusUpdate>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(BatchPatchSubStatusArgs { updates }, callback)
    }
}
