// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BurnIdSequenceArgs {
    pub table: String,
    pub ceiling: i64,
}

impl From<BurnIdSequenceArgs> for super::Reducer {
    fn from(args: BurnIdSequenceArgs) -> Self {
        Self::BurnIdSequence {
            table: args.table,
            ceiling: args.ceiling,
        }
    }
}

impl __sdk::InModule for BurnIdSequenceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `burn_id_sequence`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait burn_id_sequence {
    /// Request that the remote module invoke the reducer `burn_id_sequence` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`burn_id_sequence:burn_id_sequence_then`] to run a callback after the reducer completes.
    fn burn_id_sequence(&self, table: String, ceiling: i64) -> __sdk::Result<()> {
        self.burn_id_sequence_then(table, ceiling, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `burn_id_sequence` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn burn_id_sequence_then(
        &self,
        table: String,
        ceiling: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl burn_id_sequence for super::RemoteReducers {
    fn burn_id_sequence_then(
        &self,
        table: String,
        ceiling: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(BurnIdSequenceArgs { table, ceiling }, callback)
    }
}
