// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimBacklogTaskArgs {
    pub id: i64,
    pub host: String,
}

impl From<ClaimBacklogTaskArgs> for super::Reducer {
    fn from(args: ClaimBacklogTaskArgs) -> Self {
        Self::ClaimBacklogTask {
            id: args.id,
            host: args.host,
        }
    }
}

impl __sdk::InModule for ClaimBacklogTaskArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_backlog_task`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_backlog_task {
    /// Request that the remote module invoke the reducer `claim_backlog_task` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_backlog_task:claim_backlog_task_then`] to run a callback after the reducer completes.
    fn claim_backlog_task(&self, id: i64, host: String) -> __sdk::Result<()> {
        self.claim_backlog_task_then(id, host, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_backlog_task` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_backlog_task_then(
        &self,
        id: i64,
        host: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_backlog_task for super::RemoteReducers {
    fn claim_backlog_task_then(
        &self,
        id: i64,
        host: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ClaimBacklogTaskArgs { id, host }, callback)
    }
}
