// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateRepoGroupSubEpicArgs {
    pub parent_id: i64,
    pub title: String,
    pub created_by: String,
}

impl From<CreateRepoGroupSubEpicArgs> for super::Reducer {
    fn from(args: CreateRepoGroupSubEpicArgs) -> Self {
        Self::CreateRepoGroupSubEpic {
            parent_id: args.parent_id,
            title: args.title,
            created_by: args.created_by,
        }
    }
}

impl __sdk::InModule for CreateRepoGroupSubEpicArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_repo_group_sub_epic`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_repo_group_sub_epic {
    /// Request that the remote module invoke the reducer `create_repo_group_sub_epic` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_repo_group_sub_epic:create_repo_group_sub_epic_then`] to run a callback after the reducer completes.
    fn create_repo_group_sub_epic(
        &self,
        parent_id: i64,
        title: String,
        created_by: String,
    ) -> __sdk::Result<()> {
        self.create_repo_group_sub_epic_then(parent_id, title, created_by, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_repo_group_sub_epic` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_repo_group_sub_epic_then(
        &self,
        parent_id: i64,
        title: String,
        created_by: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_repo_group_sub_epic for super::RemoteReducers {
    fn create_repo_group_sub_epic_then(
        &self,
        parent_id: i64,
        title: String,
        created_by: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateRepoGroupSubEpicArgs {
                parent_id,
                title,
                created_by,
            },
            callback,
        )
    }
}
