// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateManagedRoleEpicArgs {
    pub title: String,
    pub parent_epic_id: i64,
    pub role: String,
    pub feed_command: String,
    pub feed_interval_secs: i64,
    pub created_by: String,
}

impl From<CreateManagedRoleEpicArgs> for super::Reducer {
    fn from(args: CreateManagedRoleEpicArgs) -> Self {
        Self::CreateManagedRoleEpic {
            title: args.title,
            parent_epic_id: args.parent_epic_id,
            role: args.role,
            feed_command: args.feed_command,
            feed_interval_secs: args.feed_interval_secs,
            created_by: args.created_by,
        }
    }
}

impl __sdk::InModule for CreateManagedRoleEpicArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_managed_role_epic`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_managed_role_epic {
    /// Request that the remote module invoke the reducer `create_managed_role_epic` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_managed_role_epic:create_managed_role_epic_then`] to run a callback after the reducer completes.
    fn create_managed_role_epic(
        &self,
        title: String,
        parent_epic_id: i64,
        role: String,
        feed_command: String,
        feed_interval_secs: i64,
        created_by: String,
    ) -> __sdk::Result<()> {
        self.create_managed_role_epic_then(
            title,
            parent_epic_id,
            role,
            feed_command,
            feed_interval_secs,
            created_by,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_managed_role_epic` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_managed_role_epic_then(
        &self,
        title: String,
        parent_epic_id: i64,
        role: String,
        feed_command: String,
        feed_interval_secs: i64,
        created_by: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_managed_role_epic for super::RemoteReducers {
    fn create_managed_role_epic_then(
        &self,
        title: String,
        parent_epic_id: i64,
        role: String,
        feed_command: String,
        feed_interval_secs: i64,
        created_by: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateManagedRoleEpicArgs {
                title,
                parent_epic_id,
                role,
                feed_command,
                feed_interval_secs,
                created_by,
            },
            callback,
        )
    }
}
