// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateTaskWatcherArgs {
    pub watcher_task_id: i64,
    pub target_task_id: i64,
}

impl From<CreateTaskWatcherArgs> for super::Reducer {
    fn from(args: CreateTaskWatcherArgs) -> Self {
        Self::CreateTaskWatcher {
            watcher_task_id: args.watcher_task_id,
            target_task_id: args.target_task_id,
        }
    }
}

impl __sdk::InModule for CreateTaskWatcherArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_task_watcher`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_task_watcher {
    /// Request that the remote module invoke the reducer `create_task_watcher` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_task_watcher:create_task_watcher_then`] to run a callback after the reducer completes.
    fn create_task_watcher(&self, watcher_task_id: i64, target_task_id: i64) -> __sdk::Result<()> {
        self.create_task_watcher_then(watcher_task_id, target_task_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_task_watcher` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_task_watcher_then(
        &self,
        watcher_task_id: i64,
        target_task_id: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_task_watcher for super::RemoteReducers {
    fn create_task_watcher_then(
        &self,
        watcher_task_id: i64,
        target_task_id: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateTaskWatcherArgs {
                watcher_task_id,
                target_task_id,
            },
            callback,
        )
    }
}
