// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::learning_type::Learning;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateLearningArgs {
    pub row: Learning,
}

impl From<CreateLearningArgs> for super::Reducer {
    fn from(args: CreateLearningArgs) -> Self {
        Self::CreateLearning { row: args.row }
    }
}

impl __sdk::InModule for CreateLearningArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_learning`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_learning {
    /// Request that the remote module invoke the reducer `create_learning` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_learning:create_learning_then`] to run a callback after the reducer completes.
    fn create_learning(&self, row: Learning) -> __sdk::Result<()> {
        self.create_learning_then(row, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_learning` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_learning_then(
        &self,
        row: Learning,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_learning for super::RemoteReducers {
    fn create_learning_then(
        &self,
        row: Learning,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateLearningArgs { row }, callback)
    }
}
