// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteFilterPresetArgs {
    pub host: String,
    pub name: String,
}

impl From<DeleteFilterPresetArgs> for super::Reducer {
    fn from(args: DeleteFilterPresetArgs) -> Self {
        Self::DeleteFilterPreset {
            host: args.host,
            name: args.name,
        }
    }
}

impl __sdk::InModule for DeleteFilterPresetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_filter_preset`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_filter_preset {
    /// Request that the remote module invoke the reducer `delete_filter_preset` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`delete_filter_preset:delete_filter_preset_then`] to run a callback after the reducer completes.
    fn delete_filter_preset(&self, host: String, name: String) -> __sdk::Result<()> {
        self.delete_filter_preset_then(host, name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `delete_filter_preset` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn delete_filter_preset_then(
        &self,
        host: String,
        name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_filter_preset for super::RemoteReducers {
    fn delete_filter_preset_then(
        &self,
        host: String,
        name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DeleteFilterPresetArgs { host, name }, callback)
    }
}
