// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DropClosedRetiredFeedItemsArgs {
    pub feed_epic_id: i64,
    pub keep_external_ids: Vec<String>,
}

impl From<DropClosedRetiredFeedItemsArgs> for super::Reducer {
    fn from(args: DropClosedRetiredFeedItemsArgs) -> Self {
        Self::DropClosedRetiredFeedItems {
            feed_epic_id: args.feed_epic_id,
            keep_external_ids: args.keep_external_ids,
        }
    }
}

impl __sdk::InModule for DropClosedRetiredFeedItemsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `drop_closed_retired_feed_items`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait drop_closed_retired_feed_items {
    /// Request that the remote module invoke the reducer `drop_closed_retired_feed_items` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`drop_closed_retired_feed_items:drop_closed_retired_feed_items_then`] to run a callback after the reducer completes.
    fn drop_closed_retired_feed_items(
        &self,
        feed_epic_id: i64,
        keep_external_ids: Vec<String>,
    ) -> __sdk::Result<()> {
        self.drop_closed_retired_feed_items_then(feed_epic_id, keep_external_ids, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `drop_closed_retired_feed_items` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn drop_closed_retired_feed_items_then(
        &self,
        feed_epic_id: i64,
        keep_external_ids: Vec<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl drop_closed_retired_feed_items for super::RemoteReducers {
    fn drop_closed_retired_feed_items_then(
        &self,
        feed_epic_id: i64,
        keep_external_ids: Vec<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DropClosedRetiredFeedItemsArgs {
                feed_epic_id,
                keep_external_ids,
            },
            callback,
        )
    }
}
