// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Epic {
    pub id: i64,
    pub title: String,
    pub description: String,
    pub status: String,
    pub plan_path: String,
    pub sort_order: Option<i64>,
    pub created_at: String,
    pub updated_at: String,
    pub auto_dispatch: bool,
    pub parent_epic_id: i64,
    pub feed_command: String,
    pub feed_interval_secs: i64,
    pub group_by_repo: bool,
    pub feed_role: String,
    pub origin: String,
    pub feed_append_only: bool,
}

impl __sdk::InModule for Epic {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Epic`.
///
/// Provides typed access to columns for query building.
pub struct EpicCols {
    pub id: __sdk::__query_builder::Col<Epic, i64>,
    pub title: __sdk::__query_builder::Col<Epic, String>,
    pub description: __sdk::__query_builder::Col<Epic, String>,
    pub status: __sdk::__query_builder::Col<Epic, String>,
    pub plan_path: __sdk::__query_builder::Col<Epic, String>,
    pub sort_order: __sdk::__query_builder::Col<Epic, Option<i64>>,
    pub created_at: __sdk::__query_builder::Col<Epic, String>,
    pub updated_at: __sdk::__query_builder::Col<Epic, String>,
    pub auto_dispatch: __sdk::__query_builder::Col<Epic, bool>,
    pub parent_epic_id: __sdk::__query_builder::Col<Epic, i64>,
    pub feed_command: __sdk::__query_builder::Col<Epic, String>,
    pub feed_interval_secs: __sdk::__query_builder::Col<Epic, i64>,
    pub group_by_repo: __sdk::__query_builder::Col<Epic, bool>,
    pub feed_role: __sdk::__query_builder::Col<Epic, String>,
    pub origin: __sdk::__query_builder::Col<Epic, String>,
    pub feed_append_only: __sdk::__query_builder::Col<Epic, bool>,
}

impl __sdk::__query_builder::HasCols for Epic {
    type Cols = EpicCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EpicCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            plan_path: __sdk::__query_builder::Col::new(table_name, "plan_path"),
            sort_order: __sdk::__query_builder::Col::new(table_name, "sort_order"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            auto_dispatch: __sdk::__query_builder::Col::new(table_name, "auto_dispatch"),
            parent_epic_id: __sdk::__query_builder::Col::new(table_name, "parent_epic_id"),
            feed_command: __sdk::__query_builder::Col::new(table_name, "feed_command"),
            feed_interval_secs: __sdk::__query_builder::Col::new(table_name, "feed_interval_secs"),
            group_by_repo: __sdk::__query_builder::Col::new(table_name, "group_by_repo"),
            feed_role: __sdk::__query_builder::Col::new(table_name, "feed_role"),
            origin: __sdk::__query_builder::Col::new(table_name, "origin"),
            feed_append_only: __sdk::__query_builder::Col::new(table_name, "feed_append_only"),
        }
    }
}

/// Indexed column accessor struct for the table `Epic`.
///
/// Provides typed access to indexed columns for query building.
pub struct EpicIxCols {
    pub id: __sdk::__query_builder::IxCol<Epic, i64>,
}

impl __sdk::__query_builder::HasIxCols for Epic {
    type IxCols = EpicIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EpicIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Epic {}
