// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FilterPreset {
    pub id: String,
    pub host: String,
    pub name: String,
    pub repo_paths: String,
    pub mode: String,
}

impl __sdk::InModule for FilterPreset {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `FilterPreset`.
///
/// Provides typed access to columns for query building.
pub struct FilterPresetCols {
    pub id: __sdk::__query_builder::Col<FilterPreset, String>,
    pub host: __sdk::__query_builder::Col<FilterPreset, String>,
    pub name: __sdk::__query_builder::Col<FilterPreset, String>,
    pub repo_paths: __sdk::__query_builder::Col<FilterPreset, String>,
    pub mode: __sdk::__query_builder::Col<FilterPreset, String>,
}

impl __sdk::__query_builder::HasCols for FilterPreset {
    type Cols = FilterPresetCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FilterPresetCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            host: __sdk::__query_builder::Col::new(table_name, "host"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            repo_paths: __sdk::__query_builder::Col::new(table_name, "repo_paths"),
            mode: __sdk::__query_builder::Col::new(table_name, "mode"),
        }
    }
}

/// Indexed column accessor struct for the table `FilterPreset`.
///
/// Provides typed access to indexed columns for query building.
pub struct FilterPresetIxCols {
    pub host: __sdk::__query_builder::IxCol<FilterPreset, String>,
    pub id: __sdk::__query_builder::IxCol<FilterPreset, String>,
}

impl __sdk::__query_builder::HasIxCols for FilterPreset {
    type IxCols = FilterPresetIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FilterPresetIxCols {
            host: __sdk::__query_builder::IxCol::new(table_name, "host"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for FilterPreset {}
