// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Host {
    pub id: String,
    pub label: String,
    pub owner: String,
}

impl __sdk::InModule for Host {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Host`.
///
/// Provides typed access to columns for query building.
pub struct HostCols {
    pub id: __sdk::__query_builder::Col<Host, String>,
    pub label: __sdk::__query_builder::Col<Host, String>,
    pub owner: __sdk::__query_builder::Col<Host, String>,
}

impl __sdk::__query_builder::HasCols for Host {
    type Cols = HostCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HostCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            label: __sdk::__query_builder::Col::new(table_name, "label"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
        }
    }
}

/// Indexed column accessor struct for the table `Host`.
///
/// Provides typed access to indexed columns for query building.
pub struct HostIxCols {
    pub id: __sdk::__query_builder::IxCol<Host, String>,
}

impl __sdk::__query_builder::HasIxCols for Host {
    type IxCols = HostIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HostIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Host {}
