// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LearningRetrieval {
    pub id: i64,
    pub task_id: i64,
    pub learning_id: i64,
    pub source: String,
    pub retrieved_at: String,
}

impl __sdk::InModule for LearningRetrieval {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LearningRetrieval`.
///
/// Provides typed access to columns for query building.
pub struct LearningRetrievalCols {
    pub id: __sdk::__query_builder::Col<LearningRetrieval, i64>,
    pub task_id: __sdk::__query_builder::Col<LearningRetrieval, i64>,
    pub learning_id: __sdk::__query_builder::Col<LearningRetrieval, i64>,
    pub source: __sdk::__query_builder::Col<LearningRetrieval, String>,
    pub retrieved_at: __sdk::__query_builder::Col<LearningRetrieval, String>,
}

impl __sdk::__query_builder::HasCols for LearningRetrieval {
    type Cols = LearningRetrievalCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LearningRetrievalCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            task_id: __sdk::__query_builder::Col::new(table_name, "task_id"),
            learning_id: __sdk::__query_builder::Col::new(table_name, "learning_id"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            retrieved_at: __sdk::__query_builder::Col::new(table_name, "retrieved_at"),
        }
    }
}

/// Indexed column accessor struct for the table `LearningRetrieval`.
///
/// Provides typed access to indexed columns for query building.
pub struct LearningRetrievalIxCols {
    pub id: __sdk::__query_builder::IxCol<LearningRetrieval, i64>,
    pub learning_id: __sdk::__query_builder::IxCol<LearningRetrieval, i64>,
    pub task_id: __sdk::__query_builder::IxCol<LearningRetrieval, i64>,
}

impl __sdk::__query_builder::HasIxCols for LearningRetrieval {
    type IxCols = LearningRetrievalIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LearningRetrievalIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            learning_id: __sdk::__query_builder::IxCol::new(table_name, "learning_id"),
            task_id: __sdk::__query_builder::IxCol::new(table_name, "task_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LearningRetrieval {}
