// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Learning {
    pub id: i64,
    pub kind: String,
    pub summary: String,
    pub detail: Option<String>,
    pub scope: String,
    pub scope_ref: Option<String>,
    pub tags: String,
    pub status: String,
    pub source_task_id: Option<i64>,
    pub upvote_count: i64,
    pub last_upvoted_at: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub embedding: Option<Vec<u8>>,
}

impl __sdk::InModule for Learning {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Learning`.
///
/// Provides typed access to columns for query building.
pub struct LearningCols {
    pub id: __sdk::__query_builder::Col<Learning, i64>,
    pub kind: __sdk::__query_builder::Col<Learning, String>,
    pub summary: __sdk::__query_builder::Col<Learning, String>,
    pub detail: __sdk::__query_builder::Col<Learning, Option<String>>,
    pub scope: __sdk::__query_builder::Col<Learning, String>,
    pub scope_ref: __sdk::__query_builder::Col<Learning, Option<String>>,
    pub tags: __sdk::__query_builder::Col<Learning, String>,
    pub status: __sdk::__query_builder::Col<Learning, String>,
    pub source_task_id: __sdk::__query_builder::Col<Learning, Option<i64>>,
    pub upvote_count: __sdk::__query_builder::Col<Learning, i64>,
    pub last_upvoted_at: __sdk::__query_builder::Col<Learning, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<Learning, String>,
    pub updated_at: __sdk::__query_builder::Col<Learning, String>,
    pub embedding: __sdk::__query_builder::Col<Learning, Option<Vec<u8>>>,
}

impl __sdk::__query_builder::HasCols for Learning {
    type Cols = LearningCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LearningCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            summary: __sdk::__query_builder::Col::new(table_name, "summary"),
            detail: __sdk::__query_builder::Col::new(table_name, "detail"),
            scope: __sdk::__query_builder::Col::new(table_name, "scope"),
            scope_ref: __sdk::__query_builder::Col::new(table_name, "scope_ref"),
            tags: __sdk::__query_builder::Col::new(table_name, "tags"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            source_task_id: __sdk::__query_builder::Col::new(table_name, "source_task_id"),
            upvote_count: __sdk::__query_builder::Col::new(table_name, "upvote_count"),
            last_upvoted_at: __sdk::__query_builder::Col::new(table_name, "last_upvoted_at"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            embedding: __sdk::__query_builder::Col::new(table_name, "embedding"),
        }
    }
}

/// Indexed column accessor struct for the table `Learning`.
///
/// Provides typed access to indexed columns for query building.
pub struct LearningIxCols {
    pub id: __sdk::__query_builder::IxCol<Learning, i64>,
}

impl __sdk::__query_builder::HasIxCols for Learning {
    type IxCols = LearningIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LearningIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Learning {}
