// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::learning_retrieval_type::LearningRetrieval;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `learning_retrievals`.
///
/// Obtain a handle from the [`LearningRetrievalsTableAccess::learning_retrievals`] method on [`super::RemoteTables`],
/// like `ctx.db.learning_retrievals()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.learning_retrievals().on_insert(...)`.
pub struct LearningRetrievalsTableHandle<'ctx> {
    imp: __sdk::TableHandle<LearningRetrieval>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `learning_retrievals`.
pub struct LearningRetrievalsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for LearningRetrievalsTableAccessor {
    type Row = LearningRetrieval;
    type Handle<'db> = LearningRetrievalsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.learning_retrievals()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `learning_retrievals`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LearningRetrievalsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LearningRetrievalsTableHandle`], which mediates access to the table `learning_retrievals`.
    fn learning_retrievals(&self) -> LearningRetrievalsTableHandle<'_>;
}

impl LearningRetrievalsTableAccess for super::RemoteTables {
    fn learning_retrievals(&self) -> LearningRetrievalsTableHandle<'_> {
        LearningRetrievalsTableHandle {
            imp: self
                .imp
                .get_table::<LearningRetrieval>("learning_retrievals"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LearningRetrievalsInsertCallbackId(__sdk::CallbackId);
pub struct LearningRetrievalsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for LearningRetrievalsTableHandle<'ctx> {
    type Row = LearningRetrieval;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LearningRetrieval> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for LearningRetrievalsTableHandle<'ctx> {
    type Row = LearningRetrieval;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LearningRetrieval> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LearningRetrievalsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LearningRetrievalsInsertCallbackId {
        LearningRetrievalsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LearningRetrievalsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LearningRetrievalsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LearningRetrievalsDeleteCallbackId {
        LearningRetrievalsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LearningRetrievalsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for LearningRetrievalsTableHandle<'ctx> {
    type InsertCallbackId = LearningRetrievalsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LearningRetrievalsInsertCallbackId {
        LearningRetrievalsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LearningRetrievalsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for LearningRetrievalsTableHandle<'ctx> {
    type DeleteCallbackId = LearningRetrievalsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LearningRetrievalsDeleteCallbackId {
        LearningRetrievalsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LearningRetrievalsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LearningRetrievalsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LearningRetrievalsTableHandle<'ctx> {
    type UpdateCallbackId = LearningRetrievalsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LearningRetrievalsUpdateCallbackId {
        LearningRetrievalsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LearningRetrievalsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for LearningRetrievalsTableHandle<'ctx> {
    type UpdateCallbackId = LearningRetrievalsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LearningRetrievalsUpdateCallbackId {
        LearningRetrievalsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LearningRetrievalsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `learning_retrievals`,
/// which allows point queries on the field of the same name
/// via the [`LearningRetrievalsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.learning_retrievals().id().find(...)`.
pub struct LearningRetrievalsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LearningRetrieval, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LearningRetrievalsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `learning_retrievals`.
    pub fn id(&self) -> LearningRetrievalsIdUnique<'ctx> {
        LearningRetrievalsIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LearningRetrievalsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<LearningRetrieval> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LearningRetrieval>("learning_retrievals");
    _table.add_unique_constraint::<i64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LearningRetrieval>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LearningRetrieval>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LearningRetrieval`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait learning_retrievalsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LearningRetrieval`.
    fn learning_retrievals(&self) -> __sdk::__query_builder::Table<LearningRetrieval>;
}

impl learning_retrievalsQueryTableAccess for __sdk::QueryTableAccessor {
    fn learning_retrievals(&self) -> __sdk::__query_builder::Table<LearningRetrieval> {
        __sdk::__query_builder::Table::new("learning_retrievals")
    }
}
