// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MarkPrLearningsGateShownArgs {
    pub id: i64,
    pub at: String,
}

impl From<MarkPrLearningsGateShownArgs> for super::Reducer {
    fn from(args: MarkPrLearningsGateShownArgs) -> Self {
        Self::MarkPrLearningsGateShown {
            id: args.id,
            at: args.at,
        }
    }
}

impl __sdk::InModule for MarkPrLearningsGateShownArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mark_pr_learnings_gate_shown`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mark_pr_learnings_gate_shown {
    /// Request that the remote module invoke the reducer `mark_pr_learnings_gate_shown` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`mark_pr_learnings_gate_shown:mark_pr_learnings_gate_shown_then`] to run a callback after the reducer completes.
    fn mark_pr_learnings_gate_shown(&self, id: i64, at: String) -> __sdk::Result<()> {
        self.mark_pr_learnings_gate_shown_then(id, at, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `mark_pr_learnings_gate_shown` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn mark_pr_learnings_gate_shown_then(
        &self,
        id: i64,
        at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl mark_pr_learnings_gate_shown for super::RemoteReducers {
    fn mark_pr_learnings_gate_shown_then(
        &self,
        id: i64,
        at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MarkPrLearningsGateShownArgs { id, at }, callback)
    }
}
