// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OverridePollOwnerArgs {
    pub scope: String,
    pub scope_id: i64,
    pub host: String,
}

impl From<OverridePollOwnerArgs> for super::Reducer {
    fn from(args: OverridePollOwnerArgs) -> Self {
        Self::OverridePollOwner {
            scope: args.scope,
            scope_id: args.scope_id,
            host: args.host,
        }
    }
}

impl __sdk::InModule for OverridePollOwnerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `override_poll_owner`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait override_poll_owner {
    /// Request that the remote module invoke the reducer `override_poll_owner` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`override_poll_owner:override_poll_owner_then`] to run a callback after the reducer completes.
    fn override_poll_owner(&self, scope: String, scope_id: i64, host: String) -> __sdk::Result<()> {
        self.override_poll_owner_then(scope, scope_id, host, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `override_poll_owner` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn override_poll_owner_then(
        &self,
        scope: String,
        scope_id: i64,
        host: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl override_poll_owner for super::RemoteReducers {
    fn override_poll_owner_then(
        &self,
        scope: String,
        scope_id: i64,
        host: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            OverridePollOwnerArgs {
                scope,
                scope_id,
                host,
            },
            callback,
        )
    }
}
