// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::todo_patch_type::TodoPatch;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PatchTodoArgs {
    pub id: i64,
    pub patch: TodoPatch,
}

impl From<PatchTodoArgs> for super::Reducer {
    fn from(args: PatchTodoArgs) -> Self {
        Self::PatchTodo {
            id: args.id,
            patch: args.patch,
        }
    }
}

impl __sdk::InModule for PatchTodoArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `patch_todo`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait patch_todo {
    /// Request that the remote module invoke the reducer `patch_todo` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`patch_todo:patch_todo_then`] to run a callback after the reducer completes.
    fn patch_todo(&self, id: i64, patch: TodoPatch) -> __sdk::Result<()> {
        self.patch_todo_then(id, patch, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `patch_todo` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn patch_todo_then(
        &self,
        id: i64,
        patch: TodoPatch,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl patch_todo for super::RemoteReducers {
    fn patch_todo_then(
        &self,
        id: i64,
        patch: TodoPatch,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PatchTodoArgs { id, patch }, callback)
    }
}
