// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::task_patch_type::TaskPatch;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PatchTaskArgs {
    pub id: i64,
    pub patch: TaskPatch,
}

impl From<PatchTaskArgs> for super::Reducer {
    fn from(args: PatchTaskArgs) -> Self {
        Self::PatchTask {
            id: args.id,
            patch: args.patch,
        }
    }
}

impl __sdk::InModule for PatchTaskArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `patch_task`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait patch_task {
    /// Request that the remote module invoke the reducer `patch_task` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`patch_task:patch_task_then`] to run a callback after the reducer completes.
    fn patch_task(&self, id: i64, patch: TaskPatch) -> __sdk::Result<()> {
        self.patch_task_then(id, patch, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `patch_task` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn patch_task_then(
        &self,
        id: i64,
        patch: TaskPatch,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl patch_task for super::RemoteReducers {
    fn patch_task_then(
        &self,
        id: i64,
        patch: TaskPatch,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PatchTaskArgs { id, patch }, callback)
    }
}
