// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PollOwner {
    pub id: i64,
    pub scope: String,
    pub scope_id: i64,
    pub host: String,
    pub claimed_at: String,
}

impl __sdk::InModule for PollOwner {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PollOwner`.
///
/// Provides typed access to columns for query building.
pub struct PollOwnerCols {
    pub id: __sdk::__query_builder::Col<PollOwner, i64>,
    pub scope: __sdk::__query_builder::Col<PollOwner, String>,
    pub scope_id: __sdk::__query_builder::Col<PollOwner, i64>,
    pub host: __sdk::__query_builder::Col<PollOwner, String>,
    pub claimed_at: __sdk::__query_builder::Col<PollOwner, String>,
}

impl __sdk::__query_builder::HasCols for PollOwner {
    type Cols = PollOwnerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PollOwnerCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            scope: __sdk::__query_builder::Col::new(table_name, "scope"),
            scope_id: __sdk::__query_builder::Col::new(table_name, "scope_id"),
            host: __sdk::__query_builder::Col::new(table_name, "host"),
            claimed_at: __sdk::__query_builder::Col::new(table_name, "claimed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `PollOwner`.
///
/// Provides typed access to indexed columns for query building.
pub struct PollOwnerIxCols {
    pub id: __sdk::__query_builder::IxCol<PollOwner, i64>,
    pub scope_id: __sdk::__query_builder::IxCol<PollOwner, i64>,
}

impl __sdk::__query_builder::HasIxCols for PollOwner {
    type IxCols = PollOwnerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PollOwnerIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            scope_id: __sdk::__query_builder::IxCol::new(table_name, "scope_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PollOwner {}
