// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::poll_owner_type::PollOwner;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `poll_owners`.
///
/// Obtain a handle from the [`PollOwnersTableAccess::poll_owners`] method on [`super::RemoteTables`],
/// like `ctx.db.poll_owners()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.poll_owners().on_insert(...)`.
pub struct PollOwnersTableHandle<'ctx> {
    imp: __sdk::TableHandle<PollOwner>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `poll_owners`.
pub struct PollOwnersTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PollOwnersTableAccessor {
    type Row = PollOwner;
    type Handle<'db> = PollOwnersTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.poll_owners()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `poll_owners`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PollOwnersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PollOwnersTableHandle`], which mediates access to the table `poll_owners`.
    fn poll_owners(&self) -> PollOwnersTableHandle<'_>;
}

impl PollOwnersTableAccess for super::RemoteTables {
    fn poll_owners(&self) -> PollOwnersTableHandle<'_> {
        PollOwnersTableHandle {
            imp: self.imp.get_table::<PollOwner>("poll_owners"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PollOwnersInsertCallbackId(__sdk::CallbackId);
pub struct PollOwnersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PollOwnersTableHandle<'ctx> {
    type Row = PollOwner;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PollOwner> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for PollOwnersTableHandle<'ctx> {
    type Row = PollOwner;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PollOwner> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PollOwnersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PollOwnersInsertCallbackId {
        PollOwnersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PollOwnersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PollOwnersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PollOwnersDeleteCallbackId {
        PollOwnersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PollOwnersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PollOwnersTableHandle<'ctx> {
    type InsertCallbackId = PollOwnersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PollOwnersInsertCallbackId {
        PollOwnersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PollOwnersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for PollOwnersTableHandle<'ctx> {
    type DeleteCallbackId = PollOwnersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PollOwnersDeleteCallbackId {
        PollOwnersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PollOwnersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PollOwnersUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PollOwnersTableHandle<'ctx> {
    type UpdateCallbackId = PollOwnersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PollOwnersUpdateCallbackId {
        PollOwnersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PollOwnersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for PollOwnersTableHandle<'ctx> {
    type UpdateCallbackId = PollOwnersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PollOwnersUpdateCallbackId {
        PollOwnersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PollOwnersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `poll_owners`,
/// which allows point queries on the field of the same name
/// via the [`PollOwnersIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.poll_owners().id().find(...)`.
pub struct PollOwnersIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PollOwner, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PollOwnersTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `poll_owners`.
    pub fn id(&self) -> PollOwnersIdUnique<'ctx> {
        PollOwnersIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PollOwnersIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<PollOwner> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PollOwner>("poll_owners");
    _table.add_unique_constraint::<i64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PollOwner>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PollOwner>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PollOwner`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait poll_ownersQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PollOwner`.
    fn poll_owners(&self) -> __sdk::__query_builder::Table<PollOwner>;
}

impl poll_ownersQueryTableAccess for __sdk::QueryTableAccessor {
    fn poll_owners(&self) -> __sdk::__query_builder::Table<PollOwner> {
        __sdk::__query_builder::Table::new("poll_owners")
    }
}
