// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ProbeGeneratedTaskIdArgs {}

impl From<ProbeGeneratedTaskIdArgs> for super::Reducer {
    fn from(args: ProbeGeneratedTaskIdArgs) -> Self {
        Self::ProbeGeneratedTaskId
    }
}

impl __sdk::InModule for ProbeGeneratedTaskIdArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `probe_generated_task_id`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait probe_generated_task_id {
    /// Request that the remote module invoke the reducer `probe_generated_task_id` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`probe_generated_task_id:probe_generated_task_id_then`] to run a callback after the reducer completes.
    fn probe_generated_task_id(&self) -> __sdk::Result<()> {
        self.probe_generated_task_id_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `probe_generated_task_id` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn probe_generated_task_id_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl probe_generated_task_id for super::RemoteReducers {
    fn probe_generated_task_id_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ProbeGeneratedTaskIdArgs {}, callback)
    }
}
