// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecalculateEpicStatusArgs {
    pub epic_id: i64,
}

impl From<RecalculateEpicStatusArgs> for super::Reducer {
    fn from(args: RecalculateEpicStatusArgs) -> Self {
        Self::RecalculateEpicStatus {
            epic_id: args.epic_id,
        }
    }
}

impl __sdk::InModule for RecalculateEpicStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `recalculate_epic_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait recalculate_epic_status {
    /// Request that the remote module invoke the reducer `recalculate_epic_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`recalculate_epic_status:recalculate_epic_status_then`] to run a callback after the reducer completes.
    fn recalculate_epic_status(&self, epic_id: i64) -> __sdk::Result<()> {
        self.recalculate_epic_status_then(epic_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `recalculate_epic_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn recalculate_epic_status_then(
        &self,
        epic_id: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl recalculate_epic_status for super::RemoteReducers {
    fn recalculate_epic_status_then(
        &self,
        epic_id: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RecalculateEpicStatusArgs { epic_id }, callback)
    }
}
