// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordPreToolUseArgs {
    pub id: i64,
    pub sub_status: String,
    pub at: String,
}

impl From<RecordPreToolUseArgs> for super::Reducer {
    fn from(args: RecordPreToolUseArgs) -> Self {
        Self::RecordPreToolUse {
            id: args.id,
            sub_status: args.sub_status,
            at: args.at,
        }
    }
}

impl __sdk::InModule for RecordPreToolUseArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_pre_tool_use`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_pre_tool_use {
    /// Request that the remote module invoke the reducer `record_pre_tool_use` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_pre_tool_use:record_pre_tool_use_then`] to run a callback after the reducer completes.
    fn record_pre_tool_use(&self, id: i64, sub_status: String, at: String) -> __sdk::Result<()> {
        self.record_pre_tool_use_then(id, sub_status, at, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `record_pre_tool_use` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_pre_tool_use_then(
        &self,
        id: i64,
        sub_status: String,
        at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_pre_tool_use for super::RemoteReducers {
    fn record_pre_tool_use_then(
        &self,
        id: i64,
        sub_status: String,
        at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RecordPreToolUseArgs { id, sub_status, at }, callback)
    }
}
