// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordNotificationArgs {
    pub id: i64,
    pub mode: String,
    pub at: String,
}

impl From<RecordNotificationArgs> for super::Reducer {
    fn from(args: RecordNotificationArgs) -> Self {
        Self::RecordNotification {
            id: args.id,
            mode: args.mode,
            at: args.at,
        }
    }
}

impl __sdk::InModule for RecordNotificationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_notification`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_notification {
    /// Request that the remote module invoke the reducer `record_notification` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_notification:record_notification_then`] to run a callback after the reducer completes.
    fn record_notification(&self, id: i64, mode: String, at: String) -> __sdk::Result<()> {
        self.record_notification_then(id, mode, at, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `record_notification` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_notification_then(
        &self,
        id: i64,
        mode: String,
        at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_notification for super::RemoteReducers {
    fn record_notification_then(
        &self,
        id: i64,
        mode: String,
        at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RecordNotificationArgs { id, mode, at }, callback)
    }
}
