// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::usage_event_type::UsageEvent;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordUsageEventArgs {
    pub row: UsageEvent,
    pub cap: i64,
}

impl From<RecordUsageEventArgs> for super::Reducer {
    fn from(args: RecordUsageEventArgs) -> Self {
        Self::RecordUsageEvent {
            row: args.row,
            cap: args.cap,
        }
    }
}

impl __sdk::InModule for RecordUsageEventArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_usage_event`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_usage_event {
    /// Request that the remote module invoke the reducer `record_usage_event` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_usage_event:record_usage_event_then`] to run a callback after the reducer completes.
    fn record_usage_event(&self, row: UsageEvent, cap: i64) -> __sdk::Result<()> {
        self.record_usage_event_then(row, cap, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `record_usage_event` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_usage_event_then(
        &self,
        row: UsageEvent,
        cap: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_usage_event for super::RemoteReducers {
    fn record_usage_event_then(
        &self,
        row: UsageEvent,
        cap: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RecordUsageEventArgs { row, cap }, callback)
    }
}
