// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordBaseBranchArgs {
    pub repo_path: String,
    pub branch: String,
    pub last_used: String,
}

impl From<RecordBaseBranchArgs> for super::Reducer {
    fn from(args: RecordBaseBranchArgs) -> Self {
        Self::RecordBaseBranch {
            repo_path: args.repo_path,
            branch: args.branch,
            last_used: args.last_used,
        }
    }
}

impl __sdk::InModule for RecordBaseBranchArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_base_branch`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_base_branch {
    /// Request that the remote module invoke the reducer `record_base_branch` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_base_branch:record_base_branch_then`] to run a callback after the reducer completes.
    fn record_base_branch(
        &self,
        repo_path: String,
        branch: String,
        last_used: String,
    ) -> __sdk::Result<()> {
        self.record_base_branch_then(repo_path, branch, last_used, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `record_base_branch` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_base_branch_then(
        &self,
        repo_path: String,
        branch: String,
        last_used: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_base_branch for super::RemoteReducers {
    fn record_base_branch_then(
        &self,
        repo_path: String,
        branch: String,
        last_used: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordBaseBranchArgs {
                repo_path,
                branch,
                last_used,
            },
            callback,
        )
    }
}
