// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordUserPromptSubmitArgs {
    pub id: i64,
    pub activity_at: String,
    pub prompt_at: String,
}

impl From<RecordUserPromptSubmitArgs> for super::Reducer {
    fn from(args: RecordUserPromptSubmitArgs) -> Self {
        Self::RecordUserPromptSubmit {
            id: args.id,
            activity_at: args.activity_at,
            prompt_at: args.prompt_at,
        }
    }
}

impl __sdk::InModule for RecordUserPromptSubmitArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_user_prompt_submit`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_user_prompt_submit {
    /// Request that the remote module invoke the reducer `record_user_prompt_submit` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`record_user_prompt_submit:record_user_prompt_submit_then`] to run a callback after the reducer completes.
    fn record_user_prompt_submit(
        &self,
        id: i64,
        activity_at: String,
        prompt_at: String,
    ) -> __sdk::Result<()> {
        self.record_user_prompt_submit_then(id, activity_at, prompt_at, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `record_user_prompt_submit` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn record_user_prompt_submit_then(
        &self,
        id: i64,
        activity_at: String,
        prompt_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl record_user_prompt_submit for super::RemoteReducers {
    fn record_user_prompt_submit_then(
        &self,
        id: i64,
        activity_at: String,
        prompt_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RecordUserPromptSubmitArgs {
                id,
                activity_at,
                prompt_at,
            },
            callback,
        )
    }
}
