// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterHostArgs {
    pub id: String,
    pub label: String,
    pub owner: String,
}

impl From<RegisterHostArgs> for super::Reducer {
    fn from(args: RegisterHostArgs) -> Self {
        Self::RegisterHost {
            id: args.id,
            label: args.label,
            owner: args.owner,
        }
    }
}

impl __sdk::InModule for RegisterHostArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_host`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_host {
    /// Request that the remote module invoke the reducer `register_host` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_host:register_host_then`] to run a callback after the reducer completes.
    fn register_host(&self, id: String, label: String, owner: String) -> __sdk::Result<()> {
        self.register_host_then(id, label, owner, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_host` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_host_then(
        &self,
        id: String,
        label: String,
        owner: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_host for super::RemoteReducers {
    fn register_host_then(
        &self,
        id: String,
        label: String,
        owner: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RegisterHostArgs { id, label, owner }, callback)
    }
}
