// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::repo_base_branch_type::RepoBaseBranch;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `repo_base_branches`.
///
/// Obtain a handle from the [`RepoBaseBranchesTableAccess::repo_base_branches`] method on [`super::RemoteTables`],
/// like `ctx.db.repo_base_branches()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.repo_base_branches().on_insert(...)`.
pub struct RepoBaseBranchesTableHandle<'ctx> {
    imp: __sdk::TableHandle<RepoBaseBranch>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `repo_base_branches`.
pub struct RepoBaseBranchesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for RepoBaseBranchesTableAccessor {
    type Row = RepoBaseBranch;
    type Handle<'db> = RepoBaseBranchesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.repo_base_branches()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `repo_base_branches`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RepoBaseBranchesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RepoBaseBranchesTableHandle`], which mediates access to the table `repo_base_branches`.
    fn repo_base_branches(&self) -> RepoBaseBranchesTableHandle<'_>;
}

impl RepoBaseBranchesTableAccess for super::RemoteTables {
    fn repo_base_branches(&self) -> RepoBaseBranchesTableHandle<'_> {
        RepoBaseBranchesTableHandle {
            imp: self.imp.get_table::<RepoBaseBranch>("repo_base_branches"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RepoBaseBranchesInsertCallbackId(__sdk::CallbackId);
pub struct RepoBaseBranchesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RepoBaseBranchesTableHandle<'ctx> {
    type Row = RepoBaseBranch;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RepoBaseBranch> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for RepoBaseBranchesTableHandle<'ctx> {
    type Row = RepoBaseBranch;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RepoBaseBranch> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RepoBaseBranchesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RepoBaseBranchesInsertCallbackId {
        RepoBaseBranchesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RepoBaseBranchesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RepoBaseBranchesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RepoBaseBranchesDeleteCallbackId {
        RepoBaseBranchesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RepoBaseBranchesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RepoBaseBranchesTableHandle<'ctx> {
    type InsertCallbackId = RepoBaseBranchesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RepoBaseBranchesInsertCallbackId {
        RepoBaseBranchesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RepoBaseBranchesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RepoBaseBranchesTableHandle<'ctx> {
    type DeleteCallbackId = RepoBaseBranchesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RepoBaseBranchesDeleteCallbackId {
        RepoBaseBranchesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RepoBaseBranchesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RepoBaseBranchesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RepoBaseBranchesTableHandle<'ctx> {
    type UpdateCallbackId = RepoBaseBranchesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RepoBaseBranchesUpdateCallbackId {
        RepoBaseBranchesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RepoBaseBranchesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RepoBaseBranchesTableHandle<'ctx> {
    type UpdateCallbackId = RepoBaseBranchesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RepoBaseBranchesUpdateCallbackId {
        RepoBaseBranchesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RepoBaseBranchesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `repo_base_branches`,
/// which allows point queries on the field of the same name
/// via the [`RepoBaseBranchesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.repo_base_branches().id().find(...)`.
pub struct RepoBaseBranchesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RepoBaseBranch, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RepoBaseBranchesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `repo_base_branches`.
    pub fn id(&self) -> RepoBaseBranchesIdUnique<'ctx> {
        RepoBaseBranchesIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RepoBaseBranchesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<RepoBaseBranch> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RepoBaseBranch>("repo_base_branches");
    _table.add_unique_constraint::<i64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RepoBaseBranch>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RepoBaseBranch>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RepoBaseBranch`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait repo_base_branchesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RepoBaseBranch`.
    fn repo_base_branches(&self) -> __sdk::__query_builder::Table<RepoBaseBranch>;
}

impl repo_base_branchesQueryTableAccess for __sdk::QueryTableAccessor {
    fn repo_base_branches(&self) -> __sdk::__query_builder::Table<RepoBaseBranch> {
        __sdk::__query_builder::Table::new("repo_base_branches")
    }
}
