// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RepoBaseBranch {
    pub id: i64,
    pub repo_path: String,
    pub branch: String,
    pub last_used: String,
}

impl __sdk::InModule for RepoBaseBranch {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RepoBaseBranch`.
///
/// Provides typed access to columns for query building.
pub struct RepoBaseBranchCols {
    pub id: __sdk::__query_builder::Col<RepoBaseBranch, i64>,
    pub repo_path: __sdk::__query_builder::Col<RepoBaseBranch, String>,
    pub branch: __sdk::__query_builder::Col<RepoBaseBranch, String>,
    pub last_used: __sdk::__query_builder::Col<RepoBaseBranch, String>,
}

impl __sdk::__query_builder::HasCols for RepoBaseBranch {
    type Cols = RepoBaseBranchCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RepoBaseBranchCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            repo_path: __sdk::__query_builder::Col::new(table_name, "repo_path"),
            branch: __sdk::__query_builder::Col::new(table_name, "branch"),
            last_used: __sdk::__query_builder::Col::new(table_name, "last_used"),
        }
    }
}

/// Indexed column accessor struct for the table `RepoBaseBranch`.
///
/// Provides typed access to indexed columns for query building.
pub struct RepoBaseBranchIxCols {
    pub id: __sdk::__query_builder::IxCol<RepoBaseBranch, i64>,
}

impl __sdk::__query_builder::HasIxCols for RepoBaseBranch {
    type IxCols = RepoBaseBranchIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RepoBaseBranchIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RepoBaseBranch {}
