// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RepoPath {
    pub id: i64,
    pub path: String,
    pub last_used: String,
    pub verify_command: String,
}

impl __sdk::InModule for RepoPath {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RepoPath`.
///
/// Provides typed access to columns for query building.
pub struct RepoPathCols {
    pub id: __sdk::__query_builder::Col<RepoPath, i64>,
    pub path: __sdk::__query_builder::Col<RepoPath, String>,
    pub last_used: __sdk::__query_builder::Col<RepoPath, String>,
    pub verify_command: __sdk::__query_builder::Col<RepoPath, String>,
}

impl __sdk::__query_builder::HasCols for RepoPath {
    type Cols = RepoPathCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RepoPathCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            path: __sdk::__query_builder::Col::new(table_name, "path"),
            last_used: __sdk::__query_builder::Col::new(table_name, "last_used"),
            verify_command: __sdk::__query_builder::Col::new(table_name, "verify_command"),
        }
    }
}

/// Indexed column accessor struct for the table `RepoPath`.
///
/// Provides typed access to indexed columns for query building.
pub struct RepoPathIxCols {
    pub id: __sdk::__query_builder::IxCol<RepoPath, i64>,
}

impl __sdk::__query_builder::HasIxCols for RepoPath {
    type IxCols = RepoPathIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RepoPathIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RepoPath {}
