// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::task_type::Task;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RespawnPhoenixSuccessorArgs {
    pub predecessor: i64,
    pub successor: Task,
}

impl From<RespawnPhoenixSuccessorArgs> for super::Reducer {
    fn from(args: RespawnPhoenixSuccessorArgs) -> Self {
        Self::RespawnPhoenixSuccessor {
            predecessor: args.predecessor,
            successor: args.successor,
        }
    }
}

impl __sdk::InModule for RespawnPhoenixSuccessorArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `respawn_phoenix_successor`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait respawn_phoenix_successor {
    /// Request that the remote module invoke the reducer `respawn_phoenix_successor` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`respawn_phoenix_successor:respawn_phoenix_successor_then`] to run a callback after the reducer completes.
    fn respawn_phoenix_successor(&self, predecessor: i64, successor: Task) -> __sdk::Result<()> {
        self.respawn_phoenix_successor_then(predecessor, successor, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `respawn_phoenix_successor` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn respawn_phoenix_successor_then(
        &self,
        predecessor: i64,
        successor: Task,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl respawn_phoenix_successor for super::RemoteReducers {
    fn respawn_phoenix_successor_then(
        &self,
        predecessor: i64,
        successor: Task,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RespawnPhoenixSuccessorArgs {
                predecessor,
                successor,
            },
            callback,
        )
    }
}
