// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RetiredFeedItem {
    pub id: i64,
    pub feed_epic_id: i64,
    pub external_id: String,
    pub retired_at: String,
}

impl __sdk::InModule for RetiredFeedItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RetiredFeedItem`.
///
/// Provides typed access to columns for query building.
pub struct RetiredFeedItemCols {
    pub id: __sdk::__query_builder::Col<RetiredFeedItem, i64>,
    pub feed_epic_id: __sdk::__query_builder::Col<RetiredFeedItem, i64>,
    pub external_id: __sdk::__query_builder::Col<RetiredFeedItem, String>,
    pub retired_at: __sdk::__query_builder::Col<RetiredFeedItem, String>,
}

impl __sdk::__query_builder::HasCols for RetiredFeedItem {
    type Cols = RetiredFeedItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RetiredFeedItemCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            feed_epic_id: __sdk::__query_builder::Col::new(table_name, "feed_epic_id"),
            external_id: __sdk::__query_builder::Col::new(table_name, "external_id"),
            retired_at: __sdk::__query_builder::Col::new(table_name, "retired_at"),
        }
    }
}

/// Indexed column accessor struct for the table `RetiredFeedItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct RetiredFeedItemIxCols {
    pub feed_epic_id: __sdk::__query_builder::IxCol<RetiredFeedItem, i64>,
    pub id: __sdk::__query_builder::IxCol<RetiredFeedItem, i64>,
}

impl __sdk::__query_builder::HasIxCols for RetiredFeedItem {
    type IxCols = RetiredFeedItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RetiredFeedItemIxCols {
            feed_epic_id: __sdk::__query_builder::IxCol::new(table_name, "feed_epic_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RetiredFeedItem {}
