// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::retired_feed_item_type::RetiredFeedItem;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `retired_feed_items`.
///
/// Obtain a handle from the [`RetiredFeedItemsTableAccess::retired_feed_items`] method on [`super::RemoteTables`],
/// like `ctx.db.retired_feed_items()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.retired_feed_items().on_insert(...)`.
pub struct RetiredFeedItemsTableHandle<'ctx> {
    imp: __sdk::TableHandle<RetiredFeedItem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `retired_feed_items`.
pub struct RetiredFeedItemsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for RetiredFeedItemsTableAccessor {
    type Row = RetiredFeedItem;
    type Handle<'db> = RetiredFeedItemsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.retired_feed_items()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `retired_feed_items`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RetiredFeedItemsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RetiredFeedItemsTableHandle`], which mediates access to the table `retired_feed_items`.
    fn retired_feed_items(&self) -> RetiredFeedItemsTableHandle<'_>;
}

impl RetiredFeedItemsTableAccess for super::RemoteTables {
    fn retired_feed_items(&self) -> RetiredFeedItemsTableHandle<'_> {
        RetiredFeedItemsTableHandle {
            imp: self.imp.get_table::<RetiredFeedItem>("retired_feed_items"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RetiredFeedItemsInsertCallbackId(__sdk::CallbackId);
pub struct RetiredFeedItemsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RetiredFeedItemsTableHandle<'ctx> {
    type Row = RetiredFeedItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RetiredFeedItem> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for RetiredFeedItemsTableHandle<'ctx> {
    type Row = RetiredFeedItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RetiredFeedItem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RetiredFeedItemsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RetiredFeedItemsInsertCallbackId {
        RetiredFeedItemsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RetiredFeedItemsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RetiredFeedItemsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RetiredFeedItemsDeleteCallbackId {
        RetiredFeedItemsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RetiredFeedItemsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RetiredFeedItemsTableHandle<'ctx> {
    type InsertCallbackId = RetiredFeedItemsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RetiredFeedItemsInsertCallbackId {
        RetiredFeedItemsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RetiredFeedItemsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RetiredFeedItemsTableHandle<'ctx> {
    type DeleteCallbackId = RetiredFeedItemsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RetiredFeedItemsDeleteCallbackId {
        RetiredFeedItemsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RetiredFeedItemsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RetiredFeedItemsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RetiredFeedItemsTableHandle<'ctx> {
    type UpdateCallbackId = RetiredFeedItemsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RetiredFeedItemsUpdateCallbackId {
        RetiredFeedItemsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RetiredFeedItemsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RetiredFeedItemsTableHandle<'ctx> {
    type UpdateCallbackId = RetiredFeedItemsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RetiredFeedItemsUpdateCallbackId {
        RetiredFeedItemsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RetiredFeedItemsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `retired_feed_items`,
/// which allows point queries on the field of the same name
/// via the [`RetiredFeedItemsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.retired_feed_items().id().find(...)`.
pub struct RetiredFeedItemsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RetiredFeedItem, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RetiredFeedItemsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `retired_feed_items`.
    pub fn id(&self) -> RetiredFeedItemsIdUnique<'ctx> {
        RetiredFeedItemsIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RetiredFeedItemsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<RetiredFeedItem> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RetiredFeedItem>("retired_feed_items");
    _table.add_unique_constraint::<i64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RetiredFeedItem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RetiredFeedItem>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RetiredFeedItem`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait retired_feed_itemsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RetiredFeedItem`.
    fn retired_feed_items(&self) -> __sdk::__query_builder::Table<RetiredFeedItem>;
}

impl retired_feed_itemsQueryTableAccess for __sdk::QueryTableAccessor {
    fn retired_feed_items(&self) -> __sdk::__query_builder::Table<RetiredFeedItem> {
        __sdk::__query_builder::Table::new("retired_feed_items")
    }
}
