// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SaveRepoPathArgs {
    pub path: String,
    pub last_used: String,
}

impl From<SaveRepoPathArgs> for super::Reducer {
    fn from(args: SaveRepoPathArgs) -> Self {
        Self::SaveRepoPath {
            path: args.path,
            last_used: args.last_used,
        }
    }
}

impl __sdk::InModule for SaveRepoPathArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `save_repo_path`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait save_repo_path {
    /// Request that the remote module invoke the reducer `save_repo_path` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`save_repo_path:save_repo_path_then`] to run a callback after the reducer completes.
    fn save_repo_path(&self, path: String, last_used: String) -> __sdk::Result<()> {
        self.save_repo_path_then(path, last_used, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `save_repo_path` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn save_repo_path_then(
        &self,
        path: String,
        last_used: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl save_repo_path for super::RemoteReducers {
    fn save_repo_path_then(
        &self,
        path: String,
        last_used: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SaveRepoPathArgs { path, last_used }, callback)
    }
}
