// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SaveFilterPresetArgs {
    pub host: String,
    pub name: String,
    pub repo_paths: String,
    pub mode: String,
}

impl From<SaveFilterPresetArgs> for super::Reducer {
    fn from(args: SaveFilterPresetArgs) -> Self {
        Self::SaveFilterPreset {
            host: args.host,
            name: args.name,
            repo_paths: args.repo_paths,
            mode: args.mode,
        }
    }
}

impl __sdk::InModule for SaveFilterPresetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `save_filter_preset`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait save_filter_preset {
    /// Request that the remote module invoke the reducer `save_filter_preset` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`save_filter_preset:save_filter_preset_then`] to run a callback after the reducer completes.
    fn save_filter_preset(
        &self,
        host: String,
        name: String,
        repo_paths: String,
        mode: String,
    ) -> __sdk::Result<()> {
        self.save_filter_preset_then(host, name, repo_paths, mode, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `save_filter_preset` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn save_filter_preset_then(
        &self,
        host: String,
        name: String,
        repo_paths: String,
        mode: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl save_filter_preset for super::RemoteReducers {
    fn save_filter_preset_then(
        &self,
        host: String,
        name: String,
        repo_paths: String,
        mode: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SaveFilterPresetArgs {
                host,
                name,
                repo_paths,
                mode,
            },
            callback,
        )
    }
}
