// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SaveSettingArgs {
    pub host: String,
    pub key: String,
    pub value: String,
}

impl From<SaveSettingArgs> for super::Reducer {
    fn from(args: SaveSettingArgs) -> Self {
        Self::SaveSetting {
            host: args.host,
            key: args.key,
            value: args.value,
        }
    }
}

impl __sdk::InModule for SaveSettingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `save_setting`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait save_setting {
    /// Request that the remote module invoke the reducer `save_setting` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`save_setting:save_setting_then`] to run a callback after the reducer completes.
    fn save_setting(&self, host: String, key: String, value: String) -> __sdk::Result<()> {
        self.save_setting_then(host, key, value, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `save_setting` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn save_setting_then(
        &self,
        host: String,
        key: String,
        value: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl save_setting for super::RemoteReducers {
    fn save_setting_then(
        &self,
        host: String,
        key: String,
        value: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SaveSettingArgs { host, key, value }, callback)
    }
}
