// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SchemaVersion {
    pub id: i64,
    pub version: i64,
    pub module_version: i64,
}

impl __sdk::InModule for SchemaVersion {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SchemaVersion`.
///
/// Provides typed access to columns for query building.
pub struct SchemaVersionCols {
    pub id: __sdk::__query_builder::Col<SchemaVersion, i64>,
    pub version: __sdk::__query_builder::Col<SchemaVersion, i64>,
    pub module_version: __sdk::__query_builder::Col<SchemaVersion, i64>,
}

impl __sdk::__query_builder::HasCols for SchemaVersion {
    type Cols = SchemaVersionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SchemaVersionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            module_version: __sdk::__query_builder::Col::new(table_name, "module_version"),
        }
    }
}

/// Indexed column accessor struct for the table `SchemaVersion`.
///
/// Provides typed access to indexed columns for query building.
pub struct SchemaVersionIxCols {
    pub id: __sdk::__query_builder::IxCol<SchemaVersion, i64>,
}

impl __sdk::__query_builder::HasIxCols for SchemaVersion {
    type IxCols = SchemaVersionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SchemaVersionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SchemaVersion {}
