// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::schema_version_type::SchemaVersion;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `schema_version`.
///
/// Obtain a handle from the [`SchemaVersionTableAccess::schema_version`] method on [`super::RemoteTables`],
/// like `ctx.db.schema_version()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.schema_version().on_insert(...)`.
pub struct SchemaVersionTableHandle<'ctx> {
    imp: __sdk::TableHandle<SchemaVersion>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `schema_version`.
pub struct SchemaVersionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SchemaVersionTableAccessor {
    type Row = SchemaVersion;
    type Handle<'db> = SchemaVersionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.schema_version()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `schema_version`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SchemaVersionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SchemaVersionTableHandle`], which mediates access to the table `schema_version`.
    fn schema_version(&self) -> SchemaVersionTableHandle<'_>;
}

impl SchemaVersionTableAccess for super::RemoteTables {
    fn schema_version(&self) -> SchemaVersionTableHandle<'_> {
        SchemaVersionTableHandle {
            imp: self.imp.get_table::<SchemaVersion>("schema_version"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SchemaVersionInsertCallbackId(__sdk::CallbackId);
pub struct SchemaVersionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SchemaVersionTableHandle<'ctx> {
    type Row = SchemaVersion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SchemaVersion> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SchemaVersionTableHandle<'ctx> {
    type Row = SchemaVersion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SchemaVersion> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SchemaVersionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SchemaVersionInsertCallbackId {
        SchemaVersionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SchemaVersionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SchemaVersionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SchemaVersionDeleteCallbackId {
        SchemaVersionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SchemaVersionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SchemaVersionTableHandle<'ctx> {
    type InsertCallbackId = SchemaVersionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SchemaVersionInsertCallbackId {
        SchemaVersionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SchemaVersionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SchemaVersionTableHandle<'ctx> {
    type DeleteCallbackId = SchemaVersionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SchemaVersionDeleteCallbackId {
        SchemaVersionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SchemaVersionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SchemaVersionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SchemaVersionTableHandle<'ctx> {
    type UpdateCallbackId = SchemaVersionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SchemaVersionUpdateCallbackId {
        SchemaVersionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SchemaVersionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SchemaVersionTableHandle<'ctx> {
    type UpdateCallbackId = SchemaVersionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SchemaVersionUpdateCallbackId {
        SchemaVersionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SchemaVersionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `schema_version`,
/// which allows point queries on the field of the same name
/// via the [`SchemaVersionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.schema_version().id().find(...)`.
pub struct SchemaVersionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SchemaVersion, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SchemaVersionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `schema_version`.
    pub fn id(&self) -> SchemaVersionIdUnique<'ctx> {
        SchemaVersionIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SchemaVersionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<SchemaVersion> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SchemaVersion>("schema_version");
    _table.add_unique_constraint::<i64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SchemaVersion>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SchemaVersion>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SchemaVersion`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait schema_versionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SchemaVersion`.
    fn schema_version(&self) -> __sdk::__query_builder::Table<SchemaVersion>;
}

impl schema_versionQueryTableAccess for __sdk::QueryTableAccessor {
    fn schema_version(&self) -> __sdk::__query_builder::Table<SchemaVersion> {
        __sdk::__query_builder::Table::new("schema_version")
    }
}
