// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::host_type::Host;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedHostsArgs {
    pub rows: Vec<Host>,
}

impl From<SeedHostsArgs> for super::Reducer {
    fn from(args: SeedHostsArgs) -> Self {
        Self::SeedHosts { rows: args.rows }
    }
}

impl __sdk::InModule for SeedHostsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_hosts`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_hosts {
    /// Request that the remote module invoke the reducer `seed_hosts` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_hosts:seed_hosts_then`] to run a callback after the reducer completes.
    fn seed_hosts(&self, rows: Vec<Host>) -> __sdk::Result<()> {
        self.seed_hosts_then(rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_hosts` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_hosts_then(
        &self,
        rows: Vec<Host>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_hosts for super::RemoteReducers {
    fn seed_hosts_then(
        &self,
        rows: Vec<Host>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SeedHostsArgs { rows }, callback)
    }
}
