// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::learning_type::Learning;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedLearningsArgs {
    pub rows: Vec<Learning>,
}

impl From<SeedLearningsArgs> for super::Reducer {
    fn from(args: SeedLearningsArgs) -> Self {
        Self::SeedLearnings { rows: args.rows }
    }
}

impl __sdk::InModule for SeedLearningsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_learnings`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_learnings {
    /// Request that the remote module invoke the reducer `seed_learnings` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_learnings:seed_learnings_then`] to run a callback after the reducer completes.
    fn seed_learnings(&self, rows: Vec<Learning>) -> __sdk::Result<()> {
        self.seed_learnings_then(rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_learnings` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_learnings_then(
        &self,
        rows: Vec<Learning>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_learnings for super::RemoteReducers {
    fn seed_learnings_then(
        &self,
        rows: Vec<Learning>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SeedLearningsArgs { rows }, callback)
    }
}
