// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::repo_base_branch_type::RepoBaseBranch;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedRepoBaseBranchesArgs {
    pub rows: Vec<RepoBaseBranch>,
}

impl From<SeedRepoBaseBranchesArgs> for super::Reducer {
    fn from(args: SeedRepoBaseBranchesArgs) -> Self {
        Self::SeedRepoBaseBranches { rows: args.rows }
    }
}

impl __sdk::InModule for SeedRepoBaseBranchesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_repo_base_branches`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_repo_base_branches {
    /// Request that the remote module invoke the reducer `seed_repo_base_branches` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_repo_base_branches:seed_repo_base_branches_then`] to run a callback after the reducer completes.
    fn seed_repo_base_branches(&self, rows: Vec<RepoBaseBranch>) -> __sdk::Result<()> {
        self.seed_repo_base_branches_then(rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_repo_base_branches` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_repo_base_branches_then(
        &self,
        rows: Vec<RepoBaseBranch>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_repo_base_branches for super::RemoteReducers {
    fn seed_repo_base_branches_then(
        &self,
        rows: Vec<RepoBaseBranch>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SeedRepoBaseBranchesArgs { rows }, callback)
    }
}
