// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::learning_retrieval_type::LearningRetrieval;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedLearningRetrievalsArgs {
    pub rows: Vec<LearningRetrieval>,
}

impl From<SeedLearningRetrievalsArgs> for super::Reducer {
    fn from(args: SeedLearningRetrievalsArgs) -> Self {
        Self::SeedLearningRetrievals { rows: args.rows }
    }
}

impl __sdk::InModule for SeedLearningRetrievalsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_learning_retrievals`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_learning_retrievals {
    /// Request that the remote module invoke the reducer `seed_learning_retrievals` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_learning_retrievals:seed_learning_retrievals_then`] to run a callback after the reducer completes.
    fn seed_learning_retrievals(&self, rows: Vec<LearningRetrieval>) -> __sdk::Result<()> {
        self.seed_learning_retrievals_then(rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_learning_retrievals` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_learning_retrievals_then(
        &self,
        rows: Vec<LearningRetrieval>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_learning_retrievals for super::RemoteReducers {
    fn seed_learning_retrievals_then(
        &self,
        rows: Vec<LearningRetrieval>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SeedLearningRetrievalsArgs { rows }, callback)
    }
}
