// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::setting_type::Setting;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `settings`.
///
/// Obtain a handle from the [`SettingsTableAccess::settings`] method on [`super::RemoteTables`],
/// like `ctx.db.settings()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.settings().on_insert(...)`.
pub struct SettingsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Setting>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `settings`.
pub struct SettingsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SettingsTableAccessor {
    type Row = Setting;
    type Handle<'db> = SettingsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.settings()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `settings`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SettingsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SettingsTableHandle`], which mediates access to the table `settings`.
    fn settings(&self) -> SettingsTableHandle<'_>;
}

impl SettingsTableAccess for super::RemoteTables {
    fn settings(&self) -> SettingsTableHandle<'_> {
        SettingsTableHandle {
            imp: self.imp.get_table::<Setting>("settings"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SettingsInsertCallbackId(__sdk::CallbackId);
pub struct SettingsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SettingsTableHandle<'ctx> {
    type Row = Setting;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Setting> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SettingsTableHandle<'ctx> {
    type Row = Setting;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Setting> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SettingsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SettingsInsertCallbackId {
        SettingsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SettingsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SettingsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SettingsDeleteCallbackId {
        SettingsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SettingsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SettingsTableHandle<'ctx> {
    type InsertCallbackId = SettingsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SettingsInsertCallbackId {
        SettingsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SettingsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SettingsTableHandle<'ctx> {
    type DeleteCallbackId = SettingsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SettingsDeleteCallbackId {
        SettingsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SettingsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SettingsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SettingsTableHandle<'ctx> {
    type UpdateCallbackId = SettingsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SettingsUpdateCallbackId {
        SettingsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SettingsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SettingsTableHandle<'ctx> {
    type UpdateCallbackId = SettingsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SettingsUpdateCallbackId {
        SettingsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SettingsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `settings`,
/// which allows point queries on the field of the same name
/// via the [`SettingsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.settings().id().find(...)`.
pub struct SettingsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Setting, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SettingsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `settings`.
    pub fn id(&self) -> SettingsIdUnique<'ctx> {
        SettingsIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SettingsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Setting> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Setting>("settings");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Setting>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Setting>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Setting`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait settingsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Setting`.
    fn settings(&self) -> __sdk::__query_builder::Table<Setting>;
}

impl settingsQueryTableAccess for __sdk::QueryTableAccessor {
    fn settings(&self) -> __sdk::__query_builder::Table<Setting> {
        __sdk::__query_builder::Table::new("settings")
    }
}
