// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ShellStopArgs {
    pub task_id: i64,
    pub shell_id: String,
    pub session_id: String,
}

impl From<ShellStopArgs> for super::Reducer {
    fn from(args: ShellStopArgs) -> Self {
        Self::ShellStop {
            task_id: args.task_id,
            shell_id: args.shell_id,
            session_id: args.session_id,
        }
    }
}

impl __sdk::InModule for ShellStopArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `shell_stop`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait shell_stop {
    /// Request that the remote module invoke the reducer `shell_stop` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`shell_stop:shell_stop_then`] to run a callback after the reducer completes.
    fn shell_stop(&self, task_id: i64, shell_id: String, session_id: String) -> __sdk::Result<()> {
        self.shell_stop_then(task_id, shell_id, session_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `shell_stop` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn shell_stop_then(
        &self,
        task_id: i64,
        shell_id: String,
        session_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl shell_stop for super::RemoteReducers {
    fn shell_stop_then(
        &self,
        task_id: i64,
        shell_id: String,
        session_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ShellStopArgs {
                task_id,
                shell_id,
                session_id,
            },
            callback,
        )
    }
}
