// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ShellClearNoDrainArgs {
    pub task_id: i64,
}

impl From<ShellClearNoDrainArgs> for super::Reducer {
    fn from(args: ShellClearNoDrainArgs) -> Self {
        Self::ShellClearNoDrain {
            task_id: args.task_id,
        }
    }
}

impl __sdk::InModule for ShellClearNoDrainArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `shell_clear_no_drain`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait shell_clear_no_drain {
    /// Request that the remote module invoke the reducer `shell_clear_no_drain` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`shell_clear_no_drain:shell_clear_no_drain_then`] to run a callback after the reducer completes.
    fn shell_clear_no_drain(&self, task_id: i64) -> __sdk::Result<()> {
        self.shell_clear_no_drain_then(task_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `shell_clear_no_drain` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn shell_clear_no_drain_then(
        &self,
        task_id: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl shell_clear_no_drain for super::RemoteReducers {
    fn shell_clear_no_drain_then(
        &self,
        task_id: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ShellClearNoDrainArgs { task_id }, callback)
    }
}
