// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Subscription {
    pub id: String,
    pub epic_id: i64,
    pub subscriber: String,
}

impl __sdk::InModule for Subscription {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Subscription`.
///
/// Provides typed access to columns for query building.
pub struct SubscriptionCols {
    pub id: __sdk::__query_builder::Col<Subscription, String>,
    pub epic_id: __sdk::__query_builder::Col<Subscription, i64>,
    pub subscriber: __sdk::__query_builder::Col<Subscription, String>,
}

impl __sdk::__query_builder::HasCols for Subscription {
    type Cols = SubscriptionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SubscriptionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            epic_id: __sdk::__query_builder::Col::new(table_name, "epic_id"),
            subscriber: __sdk::__query_builder::Col::new(table_name, "subscriber"),
        }
    }
}

/// Indexed column accessor struct for the table `Subscription`.
///
/// Provides typed access to indexed columns for query building.
pub struct SubscriptionIxCols {
    pub id: __sdk::__query_builder::IxCol<Subscription, String>,
}

impl __sdk::__query_builder::HasIxCols for Subscription {
    type IxCols = SubscriptionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SubscriptionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Subscription {}
