// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubscribeToEpicArgs {
    pub subscriber: String,
    pub epic_id: i64,
}

impl From<SubscribeToEpicArgs> for super::Reducer {
    fn from(args: SubscribeToEpicArgs) -> Self {
        Self::SubscribeToEpic {
            subscriber: args.subscriber,
            epic_id: args.epic_id,
        }
    }
}

impl __sdk::InModule for SubscribeToEpicArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `subscribe_to_epic`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait subscribe_to_epic {
    /// Request that the remote module invoke the reducer `subscribe_to_epic` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`subscribe_to_epic:subscribe_to_epic_then`] to run a callback after the reducer completes.
    fn subscribe_to_epic(&self, subscriber: String, epic_id: i64) -> __sdk::Result<()> {
        self.subscribe_to_epic_then(subscriber, epic_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `subscribe_to_epic` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn subscribe_to_epic_then(
        &self,
        subscriber: String,
        epic_id: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl subscribe_to_epic for super::RemoteReducers {
    fn subscribe_to_epic_then(
        &self,
        subscriber: String,
        epic_id: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SubscribeToEpicArgs {
                subscriber,
                epic_id,
            },
            callback,
        )
    }
}
