// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::task_shell_type::TaskShell;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `task_shells`.
///
/// Obtain a handle from the [`TaskShellsTableAccess::task_shells`] method on [`super::RemoteTables`],
/// like `ctx.db.task_shells()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.task_shells().on_insert(...)`.
pub struct TaskShellsTableHandle<'ctx> {
    imp: __sdk::TableHandle<TaskShell>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `task_shells`.
pub struct TaskShellsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for TaskShellsTableAccessor {
    type Row = TaskShell;
    type Handle<'db> = TaskShellsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.task_shells()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `task_shells`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TaskShellsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TaskShellsTableHandle`], which mediates access to the table `task_shells`.
    fn task_shells(&self) -> TaskShellsTableHandle<'_>;
}

impl TaskShellsTableAccess for super::RemoteTables {
    fn task_shells(&self) -> TaskShellsTableHandle<'_> {
        TaskShellsTableHandle {
            imp: self.imp.get_table::<TaskShell>("task_shells"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TaskShellsInsertCallbackId(__sdk::CallbackId);
pub struct TaskShellsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for TaskShellsTableHandle<'ctx> {
    type Row = TaskShell;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TaskShell> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for TaskShellsTableHandle<'ctx> {
    type Row = TaskShell;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TaskShell> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TaskShellsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskShellsInsertCallbackId {
        TaskShellsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TaskShellsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TaskShellsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskShellsDeleteCallbackId {
        TaskShellsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TaskShellsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for TaskShellsTableHandle<'ctx> {
    type InsertCallbackId = TaskShellsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskShellsInsertCallbackId {
        TaskShellsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TaskShellsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for TaskShellsTableHandle<'ctx> {
    type DeleteCallbackId = TaskShellsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskShellsDeleteCallbackId {
        TaskShellsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TaskShellsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TaskShell>("task_shells");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TaskShell>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TaskShell>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TaskShell`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait task_shellsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TaskShell`.
    fn task_shells(&self) -> __sdk::__query_builder::Table<TaskShell>;
}

impl task_shellsQueryTableAccess for __sdk::QueryTableAccessor {
    fn task_shells(&self) -> __sdk::__query_builder::Table<TaskShell> {
        __sdk::__query_builder::Table::new("task_shells")
    }
}
