// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Task {
    pub id: i64,
    pub title: String,
    pub description: String,
    pub repo_path: String,
    pub status: String,
    pub worktree: String,
    pub tmux_window: String,
    pub plan_path: String,
    pub epic_id: i64,
    pub sub_status: String,
    pub tag: String,
    pub sort_order: Option<i64>,
    pub created_at: String,
    pub updated_at: String,
    pub base_branch: String,
    pub external_id: String,
    pub labels: String,
    pub last_pre_tool_use_at: String,
    pub last_notification_at: String,
    pub wrap_up_mode: String,
    pub url: String,
    pub url_type: String,
    pub pr_learnings_gate_shown_at: String,
    pub auto_run_plan: bool,
    pub live_subagents: i64,
    pub stop_pending: bool,
    pub stop_pending_at: String,
    pub live_shells: i64,
    pub oldest_live_shell_started_at: String,
    pub last_peer_message_sent_at: String,
    pub last_peer_message_received_at: String,
    pub phoenix: bool,
    pub host: String,
    pub owner: String,
    pub completed_at: String,
}

impl __sdk::InModule for Task {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Task`.
///
/// Provides typed access to columns for query building.
pub struct TaskCols {
    pub id: __sdk::__query_builder::Col<Task, i64>,
    pub title: __sdk::__query_builder::Col<Task, String>,
    pub description: __sdk::__query_builder::Col<Task, String>,
    pub repo_path: __sdk::__query_builder::Col<Task, String>,
    pub status: __sdk::__query_builder::Col<Task, String>,
    pub worktree: __sdk::__query_builder::Col<Task, String>,
    pub tmux_window: __sdk::__query_builder::Col<Task, String>,
    pub plan_path: __sdk::__query_builder::Col<Task, String>,
    pub epic_id: __sdk::__query_builder::Col<Task, i64>,
    pub sub_status: __sdk::__query_builder::Col<Task, String>,
    pub tag: __sdk::__query_builder::Col<Task, String>,
    pub sort_order: __sdk::__query_builder::Col<Task, Option<i64>>,
    pub created_at: __sdk::__query_builder::Col<Task, String>,
    pub updated_at: __sdk::__query_builder::Col<Task, String>,
    pub base_branch: __sdk::__query_builder::Col<Task, String>,
    pub external_id: __sdk::__query_builder::Col<Task, String>,
    pub labels: __sdk::__query_builder::Col<Task, String>,
    pub last_pre_tool_use_at: __sdk::__query_builder::Col<Task, String>,
    pub last_notification_at: __sdk::__query_builder::Col<Task, String>,
    pub wrap_up_mode: __sdk::__query_builder::Col<Task, String>,
    pub url: __sdk::__query_builder::Col<Task, String>,
    pub url_type: __sdk::__query_builder::Col<Task, String>,
    pub pr_learnings_gate_shown_at: __sdk::__query_builder::Col<Task, String>,
    pub auto_run_plan: __sdk::__query_builder::Col<Task, bool>,
    pub live_subagents: __sdk::__query_builder::Col<Task, i64>,
    pub stop_pending: __sdk::__query_builder::Col<Task, bool>,
    pub stop_pending_at: __sdk::__query_builder::Col<Task, String>,
    pub live_shells: __sdk::__query_builder::Col<Task, i64>,
    pub oldest_live_shell_started_at: __sdk::__query_builder::Col<Task, String>,
    pub last_peer_message_sent_at: __sdk::__query_builder::Col<Task, String>,
    pub last_peer_message_received_at: __sdk::__query_builder::Col<Task, String>,
    pub phoenix: __sdk::__query_builder::Col<Task, bool>,
    pub host: __sdk::__query_builder::Col<Task, String>,
    pub owner: __sdk::__query_builder::Col<Task, String>,
    pub completed_at: __sdk::__query_builder::Col<Task, String>,
}

impl __sdk::__query_builder::HasCols for Task {
    type Cols = TaskCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TaskCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            repo_path: __sdk::__query_builder::Col::new(table_name, "repo_path"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            worktree: __sdk::__query_builder::Col::new(table_name, "worktree"),
            tmux_window: __sdk::__query_builder::Col::new(table_name, "tmux_window"),
            plan_path: __sdk::__query_builder::Col::new(table_name, "plan_path"),
            epic_id: __sdk::__query_builder::Col::new(table_name, "epic_id"),
            sub_status: __sdk::__query_builder::Col::new(table_name, "sub_status"),
            tag: __sdk::__query_builder::Col::new(table_name, "tag"),
            sort_order: __sdk::__query_builder::Col::new(table_name, "sort_order"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            base_branch: __sdk::__query_builder::Col::new(table_name, "base_branch"),
            external_id: __sdk::__query_builder::Col::new(table_name, "external_id"),
            labels: __sdk::__query_builder::Col::new(table_name, "labels"),
            last_pre_tool_use_at: __sdk::__query_builder::Col::new(
                table_name,
                "last_pre_tool_use_at",
            ),
            last_notification_at: __sdk::__query_builder::Col::new(
                table_name,
                "last_notification_at",
            ),
            wrap_up_mode: __sdk::__query_builder::Col::new(table_name, "wrap_up_mode"),
            url: __sdk::__query_builder::Col::new(table_name, "url"),
            url_type: __sdk::__query_builder::Col::new(table_name, "url_type"),
            pr_learnings_gate_shown_at: __sdk::__query_builder::Col::new(
                table_name,
                "pr_learnings_gate_shown_at",
            ),
            auto_run_plan: __sdk::__query_builder::Col::new(table_name, "auto_run_plan"),
            live_subagents: __sdk::__query_builder::Col::new(table_name, "live_subagents"),
            stop_pending: __sdk::__query_builder::Col::new(table_name, "stop_pending"),
            stop_pending_at: __sdk::__query_builder::Col::new(table_name, "stop_pending_at"),
            live_shells: __sdk::__query_builder::Col::new(table_name, "live_shells"),
            oldest_live_shell_started_at: __sdk::__query_builder::Col::new(
                table_name,
                "oldest_live_shell_started_at",
            ),
            last_peer_message_sent_at: __sdk::__query_builder::Col::new(
                table_name,
                "last_peer_message_sent_at",
            ),
            last_peer_message_received_at: __sdk::__query_builder::Col::new(
                table_name,
                "last_peer_message_received_at",
            ),
            phoenix: __sdk::__query_builder::Col::new(table_name, "phoenix"),
            host: __sdk::__query_builder::Col::new(table_name, "host"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            completed_at: __sdk::__query_builder::Col::new(table_name, "completed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Task`.
///
/// Provides typed access to indexed columns for query building.
pub struct TaskIxCols {
    pub id: __sdk::__query_builder::IxCol<Task, i64>,
}

impl __sdk::__query_builder::HasIxCols for Task {
    type IxCols = TaskIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TaskIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Task {}
