// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::task_watcher_type::TaskWatcher;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `task_watchers`.
///
/// Obtain a handle from the [`TaskWatchersTableAccess::task_watchers`] method on [`super::RemoteTables`],
/// like `ctx.db.task_watchers()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.task_watchers().on_insert(...)`.
pub struct TaskWatchersTableHandle<'ctx> {
    imp: __sdk::TableHandle<TaskWatcher>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `task_watchers`.
pub struct TaskWatchersTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for TaskWatchersTableAccessor {
    type Row = TaskWatcher;
    type Handle<'db> = TaskWatchersTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.task_watchers()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `task_watchers`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TaskWatchersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TaskWatchersTableHandle`], which mediates access to the table `task_watchers`.
    fn task_watchers(&self) -> TaskWatchersTableHandle<'_>;
}

impl TaskWatchersTableAccess for super::RemoteTables {
    fn task_watchers(&self) -> TaskWatchersTableHandle<'_> {
        TaskWatchersTableHandle {
            imp: self.imp.get_table::<TaskWatcher>("task_watchers"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TaskWatchersInsertCallbackId(__sdk::CallbackId);
pub struct TaskWatchersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for TaskWatchersTableHandle<'ctx> {
    type Row = TaskWatcher;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TaskWatcher> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for TaskWatchersTableHandle<'ctx> {
    type Row = TaskWatcher;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TaskWatcher> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TaskWatchersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskWatchersInsertCallbackId {
        TaskWatchersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TaskWatchersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TaskWatchersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskWatchersDeleteCallbackId {
        TaskWatchersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TaskWatchersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for TaskWatchersTableHandle<'ctx> {
    type InsertCallbackId = TaskWatchersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskWatchersInsertCallbackId {
        TaskWatchersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TaskWatchersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for TaskWatchersTableHandle<'ctx> {
    type DeleteCallbackId = TaskWatchersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskWatchersDeleteCallbackId {
        TaskWatchersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TaskWatchersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TaskWatchersUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TaskWatchersTableHandle<'ctx> {
    type UpdateCallbackId = TaskWatchersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TaskWatchersUpdateCallbackId {
        TaskWatchersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TaskWatchersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for TaskWatchersTableHandle<'ctx> {
    type UpdateCallbackId = TaskWatchersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TaskWatchersUpdateCallbackId {
        TaskWatchersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TaskWatchersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `task_watchers`,
/// which allows point queries on the field of the same name
/// via the [`TaskWatchersIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.task_watchers().id().find(...)`.
pub struct TaskWatchersIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TaskWatcher, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TaskWatchersTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `task_watchers`.
    pub fn id(&self) -> TaskWatchersIdUnique<'ctx> {
        TaskWatchersIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TaskWatchersIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<TaskWatcher> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TaskWatcher>("task_watchers");
    _table.add_unique_constraint::<i64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TaskWatcher>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TaskWatcher>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TaskWatcher`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait task_watchersQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TaskWatcher`.
    fn task_watchers(&self) -> __sdk::__query_builder::Table<TaskWatcher>;
}

impl task_watchersQueryTableAccess for __sdk::QueryTableAccessor {
    fn task_watchers(&self) -> __sdk::__query_builder::Table<TaskWatcher> {
        __sdk::__query_builder::Table::new("task_watchers")
    }
}
