// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TaskPatch {
    pub title: Option<String>,
    pub description: Option<String>,
    pub repo_path: Option<String>,
    pub status: Option<String>,
    pub worktree: Option<String>,
    pub tmux_window: Option<String>,
    pub plan_path: Option<String>,
    pub epic_id: Option<i64>,
    pub sub_status: Option<String>,
    pub tag: Option<String>,
    pub sort_order: Option<Option<i64>>,
    pub base_branch: Option<String>,
    pub external_id: Option<String>,
    pub labels: Option<String>,
    pub last_pre_tool_use_at: Option<String>,
    pub last_notification_at: Option<String>,
    pub wrap_up_mode: Option<String>,
    pub url: Option<String>,
    pub url_type: Option<String>,
    pub pr_learnings_gate_shown_at: Option<String>,
    pub auto_run_plan: Option<bool>,
    pub live_subagents: Option<i64>,
    pub stop_pending: Option<bool>,
    pub stop_pending_at: Option<String>,
    pub live_shells: Option<i64>,
    pub oldest_live_shell_started_at: Option<String>,
    pub last_peer_message_sent_at: Option<String>,
    pub last_peer_message_received_at: Option<String>,
    pub phoenix: Option<bool>,
    pub host: Option<String>,
    pub owner: Option<String>,
    pub completed_at: Option<String>,
}

impl __sdk::InModule for TaskPatch {
    type Module = super::RemoteModule;
}
