// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::task_subagent_type::TaskSubagent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `task_subagents`.
///
/// Obtain a handle from the [`TaskSubagentsTableAccess::task_subagents`] method on [`super::RemoteTables`],
/// like `ctx.db.task_subagents()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.task_subagents().on_insert(...)`.
pub struct TaskSubagentsTableHandle<'ctx> {
    imp: __sdk::TableHandle<TaskSubagent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `task_subagents`.
pub struct TaskSubagentsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for TaskSubagentsTableAccessor {
    type Row = TaskSubagent;
    type Handle<'db> = TaskSubagentsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.task_subagents()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `task_subagents`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TaskSubagentsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TaskSubagentsTableHandle`], which mediates access to the table `task_subagents`.
    fn task_subagents(&self) -> TaskSubagentsTableHandle<'_>;
}

impl TaskSubagentsTableAccess for super::RemoteTables {
    fn task_subagents(&self) -> TaskSubagentsTableHandle<'_> {
        TaskSubagentsTableHandle {
            imp: self.imp.get_table::<TaskSubagent>("task_subagents"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TaskSubagentsInsertCallbackId(__sdk::CallbackId);
pub struct TaskSubagentsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for TaskSubagentsTableHandle<'ctx> {
    type Row = TaskSubagent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TaskSubagent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for TaskSubagentsTableHandle<'ctx> {
    type Row = TaskSubagent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TaskSubagent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TaskSubagentsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskSubagentsInsertCallbackId {
        TaskSubagentsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TaskSubagentsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TaskSubagentsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskSubagentsDeleteCallbackId {
        TaskSubagentsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TaskSubagentsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for TaskSubagentsTableHandle<'ctx> {
    type InsertCallbackId = TaskSubagentsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskSubagentsInsertCallbackId {
        TaskSubagentsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TaskSubagentsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for TaskSubagentsTableHandle<'ctx> {
    type DeleteCallbackId = TaskSubagentsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TaskSubagentsDeleteCallbackId {
        TaskSubagentsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TaskSubagentsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TaskSubagent>("task_subagents");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TaskSubagent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TaskSubagent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TaskSubagent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait task_subagentsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TaskSubagent`.
    fn task_subagents(&self) -> __sdk::__query_builder::Table<TaskSubagent>;
}

impl task_subagentsQueryTableAccess for __sdk::QueryTableAccessor {
    fn task_subagents(&self) -> __sdk::__query_builder::Table<TaskSubagent> {
        __sdk::__query_builder::Table::new("task_subagents")
    }
}
