// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TaskShell {
    pub task_id: i64,
    pub shell_id: String,
    pub session_id: String,
    pub started_at: String,
}

impl __sdk::InModule for TaskShell {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TaskShell`.
///
/// Provides typed access to columns for query building.
pub struct TaskShellCols {
    pub task_id: __sdk::__query_builder::Col<TaskShell, i64>,
    pub shell_id: __sdk::__query_builder::Col<TaskShell, String>,
    pub session_id: __sdk::__query_builder::Col<TaskShell, String>,
    pub started_at: __sdk::__query_builder::Col<TaskShell, String>,
}

impl __sdk::__query_builder::HasCols for TaskShell {
    type Cols = TaskShellCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TaskShellCols {
            task_id: __sdk::__query_builder::Col::new(table_name, "task_id"),
            shell_id: __sdk::__query_builder::Col::new(table_name, "shell_id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TaskShell`.
///
/// Provides typed access to indexed columns for query building.
pub struct TaskShellIxCols {
    pub task_id: __sdk::__query_builder::IxCol<TaskShell, i64>,
}

impl __sdk::__query_builder::HasIxCols for TaskShell {
    type IxCols = TaskShellIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TaskShellIxCols {
            task_id: __sdk::__query_builder::IxCol::new(table_name, "task_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TaskShell {}
