// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TaskSubagent {
    pub task_id: i64,
    pub agent_id: String,
    pub session_id: String,
    pub started_at: String,
}

impl __sdk::InModule for TaskSubagent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TaskSubagent`.
///
/// Provides typed access to columns for query building.
pub struct TaskSubagentCols {
    pub task_id: __sdk::__query_builder::Col<TaskSubagent, i64>,
    pub agent_id: __sdk::__query_builder::Col<TaskSubagent, String>,
    pub session_id: __sdk::__query_builder::Col<TaskSubagent, String>,
    pub started_at: __sdk::__query_builder::Col<TaskSubagent, String>,
}

impl __sdk::__query_builder::HasCols for TaskSubagent {
    type Cols = TaskSubagentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TaskSubagentCols {
            task_id: __sdk::__query_builder::Col::new(table_name, "task_id"),
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TaskSubagent`.
///
/// Provides typed access to indexed columns for query building.
pub struct TaskSubagentIxCols {}

impl __sdk::__query_builder::HasIxCols for TaskSubagent {
    type IxCols = TaskSubagentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TaskSubagentIxCols {}
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TaskSubagent {}
