// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TaskWatcher {
    pub id: i64,
    pub watcher_task_id: i64,
    pub target_task_id: i64,
    pub created_at: String,
}

impl __sdk::InModule for TaskWatcher {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TaskWatcher`.
///
/// Provides typed access to columns for query building.
pub struct TaskWatcherCols {
    pub id: __sdk::__query_builder::Col<TaskWatcher, i64>,
    pub watcher_task_id: __sdk::__query_builder::Col<TaskWatcher, i64>,
    pub target_task_id: __sdk::__query_builder::Col<TaskWatcher, i64>,
    pub created_at: __sdk::__query_builder::Col<TaskWatcher, String>,
}

impl __sdk::__query_builder::HasCols for TaskWatcher {
    type Cols = TaskWatcherCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TaskWatcherCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            watcher_task_id: __sdk::__query_builder::Col::new(table_name, "watcher_task_id"),
            target_task_id: __sdk::__query_builder::Col::new(table_name, "target_task_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TaskWatcher`.
///
/// Provides typed access to indexed columns for query building.
pub struct TaskWatcherIxCols {
    pub id: __sdk::__query_builder::IxCol<TaskWatcher, i64>,
}

impl __sdk::__query_builder::HasIxCols for TaskWatcher {
    type IxCols = TaskWatcherIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TaskWatcherIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TaskWatcher {}
