// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Todo {
    pub id: i64,
    pub title: String,
    pub done: bool,
    pub sort_order: i64,
    pub created_at: String,
    pub task_id: i64,
    pub epic_id: i64,
    pub parent_id: i64,
    pub owner: String,
}

impl __sdk::InModule for Todo {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Todo`.
///
/// Provides typed access to columns for query building.
pub struct TodoCols {
    pub id: __sdk::__query_builder::Col<Todo, i64>,
    pub title: __sdk::__query_builder::Col<Todo, String>,
    pub done: __sdk::__query_builder::Col<Todo, bool>,
    pub sort_order: __sdk::__query_builder::Col<Todo, i64>,
    pub created_at: __sdk::__query_builder::Col<Todo, String>,
    pub task_id: __sdk::__query_builder::Col<Todo, i64>,
    pub epic_id: __sdk::__query_builder::Col<Todo, i64>,
    pub parent_id: __sdk::__query_builder::Col<Todo, i64>,
    pub owner: __sdk::__query_builder::Col<Todo, String>,
}

impl __sdk::__query_builder::HasCols for Todo {
    type Cols = TodoCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TodoCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            done: __sdk::__query_builder::Col::new(table_name, "done"),
            sort_order: __sdk::__query_builder::Col::new(table_name, "sort_order"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            task_id: __sdk::__query_builder::Col::new(table_name, "task_id"),
            epic_id: __sdk::__query_builder::Col::new(table_name, "epic_id"),
            parent_id: __sdk::__query_builder::Col::new(table_name, "parent_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
        }
    }
}

/// Indexed column accessor struct for the table `Todo`.
///
/// Provides typed access to indexed columns for query building.
pub struct TodoIxCols {
    pub id: __sdk::__query_builder::IxCol<Todo, i64>,
}

impl __sdk::__query_builder::HasIxCols for Todo {
    type IxCols = TodoIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TodoIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Todo {}
