// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TodoPatch {
    pub title: Option<String>,
    pub done: Option<bool>,
    pub sort_order: Option<i64>,
    pub task_id: Option<i64>,
    pub epic_id: Option<i64>,
    pub parent_id: Option<i64>,
    pub owner: Option<String>,
}

impl __sdk::InModule for TodoPatch {
    type Module = super::RemoteModule;
}
