// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TryRecordStopArgs {
    pub id: i64,
    pub stop_pending_at: String,
}

impl From<TryRecordStopArgs> for super::Reducer {
    fn from(args: TryRecordStopArgs) -> Self {
        Self::TryRecordStop {
            id: args.id,
            stop_pending_at: args.stop_pending_at,
        }
    }
}

impl __sdk::InModule for TryRecordStopArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `try_record_stop`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait try_record_stop {
    /// Request that the remote module invoke the reducer `try_record_stop` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`try_record_stop:try_record_stop_then`] to run a callback after the reducer completes.
    fn try_record_stop(&self, id: i64, stop_pending_at: String) -> __sdk::Result<()> {
        self.try_record_stop_then(id, stop_pending_at, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `try_record_stop` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn try_record_stop_then(
        &self,
        id: i64,
        stop_pending_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl try_record_stop for super::RemoteReducers {
    fn try_record_stop_then(
        &self,
        id: i64,
        stop_pending_at: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            TryRecordStopArgs {
                id,
                stop_pending_at,
            },
            callback,
        )
    }
}
