// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::usage_event_type::UsageEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `usage_events`.
///
/// Obtain a handle from the [`UsageEventsTableAccess::usage_events`] method on [`super::RemoteTables`],
/// like `ctx.db.usage_events()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.usage_events().on_insert(...)`.
pub struct UsageEventsTableHandle<'ctx> {
    imp: __sdk::TableHandle<UsageEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `usage_events`.
pub struct UsageEventsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for UsageEventsTableAccessor {
    type Row = UsageEvent;
    type Handle<'db> = UsageEventsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.usage_events()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `usage_events`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UsageEventsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UsageEventsTableHandle`], which mediates access to the table `usage_events`.
    fn usage_events(&self) -> UsageEventsTableHandle<'_>;
}

impl UsageEventsTableAccess for super::RemoteTables {
    fn usage_events(&self) -> UsageEventsTableHandle<'_> {
        UsageEventsTableHandle {
            imp: self.imp.get_table::<UsageEvent>("usage_events"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UsageEventsInsertCallbackId(__sdk::CallbackId);
pub struct UsageEventsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for UsageEventsTableHandle<'ctx> {
    type Row = UsageEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UsageEvent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for UsageEventsTableHandle<'ctx> {
    type Row = UsageEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UsageEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UsageEventsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UsageEventsInsertCallbackId {
        UsageEventsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UsageEventsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UsageEventsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UsageEventsDeleteCallbackId {
        UsageEventsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UsageEventsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for UsageEventsTableHandle<'ctx> {
    type InsertCallbackId = UsageEventsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UsageEventsInsertCallbackId {
        UsageEventsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UsageEventsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for UsageEventsTableHandle<'ctx> {
    type DeleteCallbackId = UsageEventsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UsageEventsDeleteCallbackId {
        UsageEventsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UsageEventsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UsageEventsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UsageEventsTableHandle<'ctx> {
    type UpdateCallbackId = UsageEventsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UsageEventsUpdateCallbackId {
        UsageEventsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UsageEventsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for UsageEventsTableHandle<'ctx> {
    type UpdateCallbackId = UsageEventsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UsageEventsUpdateCallbackId {
        UsageEventsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UsageEventsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `usage_events`,
/// which allows point queries on the field of the same name
/// via the [`UsageEventsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.usage_events().id().find(...)`.
pub struct UsageEventsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UsageEvent, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UsageEventsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `usage_events`.
    pub fn id(&self) -> UsageEventsIdUnique<'ctx> {
        UsageEventsIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UsageEventsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<UsageEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UsageEvent>("usage_events");
    _table.add_unique_constraint::<i64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UsageEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UsageEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UsageEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait usage_eventsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UsageEvent`.
    fn usage_events(&self) -> __sdk::__query_builder::Table<UsageEvent>;
}

impl usage_eventsQueryTableAccess for __sdk::QueryTableAccessor {
    fn usage_events(&self) -> __sdk::__query_builder::Table<UsageEvent> {
        __sdk::__query_builder::Table::new("usage_events")
    }
}
