// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UsageEvent {
    pub id: i64,
    pub recorded_at: String,
    pub category: String,
    pub action: String,
    pub detail: Option<String>,
    pub actor: String,
}

impl __sdk::InModule for UsageEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UsageEvent`.
///
/// Provides typed access to columns for query building.
pub struct UsageEventCols {
    pub id: __sdk::__query_builder::Col<UsageEvent, i64>,
    pub recorded_at: __sdk::__query_builder::Col<UsageEvent, String>,
    pub category: __sdk::__query_builder::Col<UsageEvent, String>,
    pub action: __sdk::__query_builder::Col<UsageEvent, String>,
    pub detail: __sdk::__query_builder::Col<UsageEvent, Option<String>>,
    pub actor: __sdk::__query_builder::Col<UsageEvent, String>,
}

impl __sdk::__query_builder::HasCols for UsageEvent {
    type Cols = UsageEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UsageEventCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            recorded_at: __sdk::__query_builder::Col::new(table_name, "recorded_at"),
            category: __sdk::__query_builder::Col::new(table_name, "category"),
            action: __sdk::__query_builder::Col::new(table_name, "action"),
            detail: __sdk::__query_builder::Col::new(table_name, "detail"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
        }
    }
}

/// Indexed column accessor struct for the table `UsageEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct UsageEventIxCols {
    pub id: __sdk::__query_builder::IxCol<UsageEvent, i64>,
}

impl __sdk::__query_builder::HasIxCols for UsageEvent {
    type IxCols = UsageEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UsageEventIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UsageEvent {}
